export const APP_ROUTES = {
  auth: {
    login: "/iniciar-sesion",
    registerOrg: "/registro-organizacion"
  },
  public: {
    book: (slug: string) => `/reservar/${slug}`,
    confirmAppointment: "/confirmar-cita",
    completePatientProfile: "/completar-perfil",
    photoUpload: (token: string) => `/movil/subida-fotos/${token}`,
    surveyResponse: (token: string) => `/publico/encuestas/responder/${token}`
  },
  dashboard: "/panel",
  healthCenter: "/centro-salud",
  agenda: {
    root: "/agenda",
    list: "/agenda/lista",
    day: "/agenda/dia",
    week: "/agenda/semana",
    month: "/agenda/mes",
    print: "/agenda/imprimir",
    reprogramming: "/agenda/reprogramacion"
  },
  patients: {
    root: "/pacientes",
    new: "/pacientes/nuevo",
    configuration: "/pacientes/configuracion",
    analysis: "/pacientes/analisis",
    orthodontia: "/pacientes/ortodoncia",
    dataQuality: "/pacientes/calidad-datos",
    merge: "/pacientes/fusion",
    detail: (id: string) => `/pacientes/${id}`,
    profile: (id: string) => `/pacientes/${id}/perfil`,
    profileBenefitsCoverages: (id: string) => `/pacientes/${id}/perfil/coberturas`,
    profileComments: (id: string) => `/pacientes/${id}/perfil/comentarios`,
    profileTasks: (id: string) => `/pacientes/${id}/perfil/tareas`,
    profileEmails: (id: string) => `/pacientes/${id}/perfil/correos`,
    profileAppointments: (id: string) => `/pacientes/${id}/perfil/citas`,
    treatments: (id: string) => `/pacientes/${id}/tratamientos`,
    treatmentNew: (id: string) => `/pacientes/${id}/tratamientos/nuevo`,
    billing: (id: string) => `/pacientes/${id}/facturacion`,
    billingPayments: (id: string) => `/pacientes/${id}/facturacion/pagos`,
    billingDocuments: (id: string) => `/pacientes/${id}/facturacion/documentos`,
    billingCoverages: (id: string) => `/pacientes/${id}/facturacion/coberturas`,
    billingReimbursements: (id: string) => `/pacientes/${id}/facturacion/coberturas/reembolsos`,
    billingOnlineBenefits: (id: string) => `/pacientes/${id}/facturacion/coberturas/beneficios-online`,
    billingRefunds: (id: string) => `/pacientes/${id}/facturacion/devoluciones`,
    billingVoided: (id: string) => `/pacientes/${id}/facturacion/anulados`,
    billingBalance: (id: string) => `/pacientes/${id}/facturacion/saldo`,
    payments: (id: string) => `/pacientes/${id}/pagos`,
    dailyReceipt: (id: string) => `/pacientes/${id}/pagos/recibo-diario`,
    clinical: (id: string) => `/pacientes/${id}/clinica`,
    clinicalHistory: (id: string) => `/pacientes/${id}/clinica/historia`,
    clinicalEvolutions: (id: string) => `/pacientes/${id}/clinica/evoluciones`,
    clinicalMedicalHistory: (id: string) => `/pacientes/${id}/clinica/anamnesis`,
    clinicalPrescriptions: (id: string) => `/pacientes/${id}/clinica/recetas`,
    clinicalDocuments: (id: string) => `/pacientes/${id}/clinica/documentos`,
    clinicalOdontogram: (id: string) => `/pacientes/${id}/clinica/odontograma`,
    clinicalPeriodontogram: (id: string) => `/pacientes/${id}/clinica/periodontograma`,
    clinicalFiles: (id: string) => `/pacientes/${id}/clinica/archivos`,
    clinicalConsents: (id: string) => `/pacientes/${id}/clinica/consentimientos`
  },
  cashRegister: {
    root: "/cajas",
    open: "/cajas/abiertas",
    closed: "/cajas/cerradas",
    reports: "/cajas/reportes",
    search: "/cajas/buscar",
    detail: (registerNumber?: string | number | null) => (registerNumber ? `/cajas/${registerNumber}` : "/cajas/cerradas")
  },
  payments: {
    root: "/pagos",
    tpv: "/pagos/tpv",
    cancelledPending: "/pagos/anulados-pendientes",
    receipt: (paymentNumber: string | number) => `/pagos/${paymentNumber}/recibo`,
    accountsReceivable: "/cuentas-por-cobrar",
    settlements: "/liquidaciones-pagos",
    installments: "/cuotas",
    collections: "/morosidad",
    collectionDetail: (id: string) => `/morosidad/${id}`
  },
  treatments: {
    plans: "/planes-tratamiento",
    budgets: "/presupuestos"
  },
  labs: {
    root: "/laboratorios",
    enabled: "/laboratorios/habilitados",
    procedures: "/laboratorios/procedimientos",
    orders: "/laboratorios/ordenes"
  },
  laboratories: {
    root: "/laboratorios",
    enabled: "/laboratorios/habilitados",
    procedures: "/laboratorios/procedimientos",
    orders: "/laboratorios/ordenes"
  },
  inventory: {
    root: "/inventario",
    movements: "/inventario/movimientos"
  },
  reports: {
    root: "/reportes",
    performance: "/reportes/desempeno",
    excel: "/reportes/excel",
    charts: "/reportes/graficos",
    appointments: "/reportes/citas",
    patients: "/reportes/pacientes",
    treatments: "/reportes/tratamientos",
    financial: "/reportes/financiero",
    professionals: "/reportes/profesionales"
  },
  crm: {
    root: "/crm",
    surveys: "/crm/encuestas",
    surveysList: "/crm/encuestas/lista",
    surveyEdit: (surveyId: string) => `/crm/encuestas/${surveyId}/editar`,
    surveySendConfig: "/crm/encuestas/configuracion-envio",
    surveyResults: "/crm/encuestas/resultados",
    emailMarketing: "/crm/email-marketing",
    emailMarketingReports: "/crm/email-marketing/reportes",
    emailMarketingReportDetail: (reportCode: string) => `/crm/email-marketing/reportes/${reportCode}`,
    emailMarketingReportCampaign: (reportCode: string) => `/crm/email-marketing/reportes/${reportCode}/campana`,
    emailMarketingCampaigns: "/crm/email-marketing/campanas",
    emailMarketingTemplates: "/crm/email-marketing/plantillas",
    emailMarketingSettings: "/crm/email-marketing/configuracion",
    tasks: "/crm/tareas",
    tasksStatistics: "/crm/tareas/estadisticas",
    tasksConfiguration: "/crm/tareas/configuracion"
  },
  settings: {
    root: "/configuracion",
    profile: "/configuracion/perfil",
    organization: "/configuracion/organizacion",
    logo: "/configuracion/logotipo",
    banks: "/configuracion/bancos",
    agreements: "/configuracion/convenios",
    expenses: "/configuracion/gastos",
    payroll: "/configuracion/nominas",
    plans: "/configuracion/planes-servicios",
    branches: "/configuracion/sucursales",
    specialties: "/configuracion/especialidades",
    onlineScheduling: "/configuracion/agenda-online",
    onlineSchedulingExpress: "/configuracion/agenda-online/express",
    onlineSchedulingSchedules: "/configuracion/agenda-online/horarios",
    onlineSchedulingCampaigns: "/configuracion/agenda-online/campanas",
    onlineSchedulingDashboard: "/configuracion/agenda-online/panel",
    schedules: "/configuracion/agenda-online/horarios",
    chairs: "/configuracion/sillones",
    paymentMethods: "/configuracion/medios-pago",
    procedures: "/configuracion/procedimientos",
    priceLists: "/configuracion/listas-precios",
    priceListCategory: (categoryId: string) => `/configuracion/listas-precios/categorias/${categoryId}`,
    consentTemplates: "/configuracion/plantillas-consentimiento",
    clinicalDocuments: "/configuracion/documentos-clinicos",
    users: "/configuracion/usuarios",
    userProfiles: "/configuracion/usuarios/perfiles",
    usersBlocksAccess: "/configuracion/usuarios/bloqueos/acceso",
    usersBlocksAgenda: "/configuracion/usuarios/bloqueos/agenda",
    usersBulkContracts: "/configuracion/usuarios/contratos/masivos",
    userContractsBulk: "/configuracion/usuarios/contratos/masivos",
    roles: "/configuracion/roles",
    roleDetail: (id: string) => `/configuracion/roles/${id}`
  }
} as const;
