import type { PermissionListItem } from "./services/permissions.service";

export const PERMISSION_LABELS: Record<string, string> = {
  "system.manage_all": "Administrar todo",
  "family_policies.read": "Ver pólizas familiares",
  "family_policies.create": "Crear pólizas familiares",
  "family_policies.manage": "Administrar pólizas familiares",
  "family_policies.activate": "Registrar pago y activar pólizas",
  "family_policies.coverage.read": "Ver coberturas de pólizas",
  "family_policies.coverage.apply": "Aplicar coberturas a tratamientos",
  "family_policies.usage.read": "Ver consumos de pólizas",
  "dashboard.read": "Ver panel principal",
  "users.read": "Ver usuarios",
  "users.create": "Crear usuarios",
  "users.update": "Editar usuarios",
  "users.deactivate": "Desactivar usuarios",
  "roles.read": "Ver perfiles",
  "roles.create": "Crear perfiles",
  "roles.update": "Editar perfiles",
  "roles.deactivate": "Desactivar perfiles",
  "permissions.read": "Ver permisos",
  "permissions.create": "Crear permisos",
  "permissions.update": "Editar permisos",
  "permissions.deactivate": "Desactivar permisos",
  "branches.read": "Ver sucursales",
  "branches.create": "Crear sucursales",
  "branches.update": "Editar sucursales",
  "branches.deactivate": "Desactivar sucursales",
  "branches.archive": "Archivar sucursales",
  "branches.restore": "Restaurar sucursales",
  "branches.assign_brand": "Mover sucursales de marca",
  "branches.manage_contact": "Editar contacto de sucursales",
  "branches.view_all": "Ver todas las sucursales",
  "health_center.view": "Ver Mi centro de salud",
  "health_center.manage": "Administrar Mi centro de salud",
  "brands.view": "Ver marcas",
  "brands.create": "Crear marcas",
  "brands.update": "Editar marcas",
  "brands.archive": "Archivar marcas",
  "brands.manage_identity": "Administrar identidad de marcas",
  "brands.manage_communications": "Administrar comunicaciones de marcas",
  "users.manage_branch_access": "Administrar acceso a sucursales",
  "settings.read": "Ver configuracion",
  "settings.update": "Editar configuracion",
  "specialties.read": "Ver especialidades",
  "specialties.create": "Crear especialidades",
  "specialties.update": "Editar especialidades",
  "specialties.deactivate": "Desactivar especialidades",
  "professionals.read": "Ver profesionales",
  "professionals.create": "Crear profesionales",
  "professionals.update": "Editar profesionales",
  "professionals.deactivate": "Desactivar profesionales",
  "schedules.read": "Ver horarios",
  "schedules.create": "Crear horarios",
  "schedules.update": "Editar horarios",
  "schedules.deactivate": "Desactivar horarios",
  "chairs.read": "Ver sillones",
  "chairs.create": "Crear sillones",
  "chairs.update": "Editar sillones",
  "chairs.deactivate": "Desactivar sillones",
  "payment_methods.read": "Ver metodos de pago",
  "payment_methods.create": "Crear metodos de pago",
  "payment_methods.update": "Editar metodos de pago",
  "payment_methods.deactivate": "Desactivar metodos de pago",
  "payment_methods.reactivate": "Reactivar medios de pago",
  "payment_methods.configure_retention": "Configurar retención de medios de pago",
  "payment_methods.configure_refunds": "Configurar devoluciones por medio",
  "payment_methods.configure_multiple_settlements": "Configurar recepciones diferidas",
  "payment_methods.configure_cash_impact": "Configurar impacto en caja y reportes",
  "payment_methods.view_audit": "Auditar medios de pago",
  "payment_settlements.read": "Ver recepciones programadas",
  "payment_settlements.receive": "Recibir vencimientos programados",
  "payment_settlements.cancel": "Cancelar vencimientos programados",
  "payment_options.cash_discounts.view": "Ver descuentos por caja",
  "payment_options.cash_discounts.create": "Crear descuentos por caja",
  "payment_options.cash_discounts.update": "Editar descuentos por caja",
  "payment_options.cash_discounts.disable": "Deshabilitar descuentos por caja",
  "payment_options.cash_discounts.reactivate": "Reactivar descuentos por caja",
  "payments.cash_discounts.apply": "Aplicar descuentos por caja",
  "payments.cash_discounts.override": "Sobrescribir limites de descuentos por caja",
  "payments.cash_discounts.view_audit": "Auditar descuentos por caja",
  "procedure_categories.read": "Ver categorias de procedimientos",
  "procedure_categories.create": "Crear categorias de procedimientos",
  "procedure_categories.update": "Editar categorias de procedimientos",
  "procedure_categories.deactivate": "Desactivar categorias de procedimientos",
  "procedures.read": "Ver procedimientos",
  "procedures.create": "Crear procedimientos",
  "procedures.update": "Editar procedimientos",
  "procedures.deactivate": "Desactivar procedimientos",
  "price_lists.read": "Ver listas de precios",
  "price_lists.create": "Crear listas de precios",
  "price_lists.update": "Editar listas de precios",
  "price_lists.configure_discount_limits": "Configurar máximos de descuento por prestación",
  "price_lists.override_manual": "Sobrescribir precios manualmente",
  "price_lists.deactivate": "Desactivar listas de precios",
  "treatment_discount.apply": "Permitir descuento",
  "treatment_discount.configure_user_limits": "Configurar máximos de descuento por usuario",
  "treatment_discount.override": "Autorizar descuentos especiales",
  "treatment_discount.view": "Ver descuentos de tratamiento",
  "treatment_discount.audit": "Auditar descuentos de tratamiento",
  "patients.read": "Ver pacientes",
  "patient_analytics.read": "Ver analisis de pacientes",
  "patient_analytics.read_financial": "Ver metricas financieras de pacientes",
  "patient_analytics.view_all_branches": "Consolidar analisis de sucursales",
  "patient_analytics.export": "Exportar analisis de pacientes",
  "patient_analytics.refresh": "Actualizar analisis de pacientes",
  "patient_analytics.view_patient_details": "Ver pacientes identificados en analisis",
  "patients.create": "Crear pacientes",
  "patients.update": "Editar pacientes",
  "patient_identity.config.read": "Ver configuración de identidad",
  "patient_identity.config.manage": "Administrar identidad de pacientes",
  "contact_points.read": "Ver medios de contacto",
  "contact_points.link": "Vincular medios de contacto",
  "contact_points.verify": "Verificar medios de contacto",
  "contact_points.transfer": "Transferir medios de contacto",
  "contact_points.backfill": "Migrar teléfonos heredados",
  "family_groups.read": "Ver grupos familiares",
  "family_groups.create": "Crear grupos familiares",
  "family_groups.manage_members": "Gestionar integrantes familiares",
  "family_groups.manage_contacts": "Gestionar contactos familiares",
  "family_groups.manage_permissions": "Gestionar permisos familiares",
  "patient_duplicates.review": "Revisar pacientes duplicados",
  "patients.merge": "Fusionar fichas de pacientes",
  "booking_identity.review": "Revisar identidad de reservas",
  "booking_identity.resolve": "Resolver identidad de reservas",
  "patients.deactivate": "Desactivar pacientes",
  "patients.notes.create": "Crear notas de pacientes",
  "patients.alerts.create": "Crear alertas de pacientes",
  "patients.tasks.read": "Ver tareas de pacientes",
  "patients.tasks.create": "Crear tareas de pacientes",
  "patients.tasks.update": "Editar tareas de pacientes",
  "patients.tasks.complete": "Finalizar tareas de pacientes",
  "appointments.read": "Ver citas",
  "appointments.create": "Crear citas",
  "appointments.update": "Editar citas",
  "appointments.cancel": "Cancelar citas",
  "appointments.status.update": "Actualizar estado de citas",
  "appointments.overbook": "Agendar fuera de disponibilidad",
  "appointments.block": "Bloquear espacios de agenda",
  "clinical.read": "Ver expediente clinico",
  "clinical.history.update": "Editar historia clinica",
  "clinical.evolutions.create": "Crear evoluciones clinicas",
  "clinical.evolutions.sign": "Firmar evoluciones clinicas",
  "clinical.prescriptions.create": "Crear recetas",
  "clinical.documents.create": "Crear documentos clinicos",
  "clinical.templates.manage": "Administrar plantillas clinicas",
  "clinical.odontogram.read": "Ver odontograma",
  "clinical.odontogram.write": "Editar odontograma",
  "clinical.periodontogram.read": "Ver periodontograma",
  "clinical.periodontogram.write": "Crear periodontograma",
  "treatment_plans.read": "Ver planes de tratamiento",
  "treatment_plans.create": "Crear planes de tratamiento",
  "treatment_plans.update": "Editar planes de tratamiento",
  "treatment_plans.status.update": "Actualizar estado de tratamientos",
  "treatment_plans.alternatives.manage": "Administrar alternativas de tratamiento",
  "orthodontic_catalogs.manage": "Administrar catalogos de ortodoncia",
  "orthodontic_diagnosis.read": "Ver diagnostico de ortodoncia",
  "orthodontic_diagnosis.create": "Guardar diagnostico activo de ortodoncia",
  "orthodontic_diagnosis.draft": "Guardar borrador de diagnostico de ortodoncia",
  "orthodontic_diagnosis.update": "Actualizar diagnostico de ortodoncia",
  "orthodontic_diagnosis.history.read": "Ver historial de diagnosticos de ortodoncia",
  "orthodontic_diagnosis.catalogs.manage": "Administrar catalogos de diagnostico de ortodoncia",
  "budgets.read": "Ver presupuestos",
  "budgets.create": "Crear presupuestos",
  "budgets.update": "Editar presupuestos",
  "budgets.send": "Enviar presupuestos",
  "budgets.accept": "Aceptar presupuestos",
  "budgets.reject": "Rechazar presupuestos",
  "budgets.print": "Imprimir presupuestos",
  "payments.read": "Ver pagos",
  "payments.create": "Registrar pagos",
  "payments.update": "Modificar pagos",
  "payments.allocate": "Asignar pagos",
  "payments.refund": "Registrar devoluciones",
  "payments.override.closed_cash": "Permitir pagos sin caja abierta",
  "payment_links.create": "Crear enlaces de pago",
  "installments.read": "Ver cuotas",
  "installments.create": "Crear cuotas",
  "installments.pay": "Registrar pago de cuotas",
  "cash_register.read": "Ver caja",
  "cash_register.open": "Abrir caja",
  "cash_register.close": "Cerrar caja",
  "cash_register.close_any": "Cerrar caja de otro usuario",
  "cash_register.move": "Registrar movimiento de caja",
  "expenses.read": "Ver gastos",
  "expenses.create": "Registrar gastos",
  "expenses.update": "Editar gastos",
  "expenses.void": "Anular gastos",
  "accounts_receivable.read": "Ver cuentas por cobrar",
  "collections.read": "Ver cobranza",
  "collections.create": "Crear casos de cobranza",
  "collections.detect": "Detectar cuentas vencidas",
  "collections.update": "Editar cobranza",
  "collections.activities.create": "Crear actividades de cobranza",
  "files.read": "Ver archivos",
  "files.upload": "Subir archivos",
  "photographic_templates.view": "Ver plantillas fotograficas",
  "photographic_templates.create": "Crear plantillas fotograficas",
  "photographic_templates.edit": "Editar plantillas fotograficas",
  "photographic_templates.void": "Anular plantillas fotograficas",
  "photographic_templates.link": "Vincular plantillas fotograficas",
  "photographic_templates.mobile_upload": "Crear carga fotografica movil",
  "photographic_templates.compare": "Comparar plantillas fotograficas",
  "photographic_templates.view_voided": "Ver plantillas fotograficas anuladas",
  "photographic_templates.configure_frequency": "Configurar frecuencia fotografica",
  "photographic_templates.configure_slots": "Configurar posiciones fotograficas",
  "photographic_photos.upload": "Subir fotografias de ortodoncia",
  "photographic_photos.edit": "Editar fotografias de ortodoncia",
  "photographic_photos.replace": "Reemplazar fotografias de ortodoncia",
  "photographic_photos.void": "Anular fotografias de ortodoncia",
  "patients.files.manage": "Administrar archivos de pacientes",
  "consent_templates.read": "Ver plantillas de consentimiento",
  "consent_templates.create": "Crear plantillas de consentimiento",
  "consent_templates.update": "Editar plantillas de consentimiento",
  "consent_templates.deactivate": "Desactivar plantillas de consentimiento",
  "consents.read": "Ver consentimientos",
  "consents.create": "Crear consentimientos",
  "consents.sign": "Firmar consentimientos",
  "consents.pdf": "Descargar PDF de consentimiento",
  "consents.templates.read": "Consultar plantillas versionadas",
  "consents.templates.create": "Crear borradores de consentimiento",
  "consents.templates.update_draft": "Editar borradores de consentimiento",
  "consents.templates.publish": "Publicar versiones de consentimiento",
  "consents.templates.deactivate": "Deshabilitar plantillas de consentimiento",
  "consents.templates.view_versions": "Consultar versiones de consentimiento",
  "consents.templates.view_audit": "Auditar plantillas de consentimiento",
  "consents.instances.read": "Consultar consentimientos clínicos",
  "consents.instances.create": "Generar consentimientos clínicos",
  "consents.instances.complete_fields": "Completar campos de consentimiento",
  "consents.instances.sign_patient": "Registrar firma del paciente",
  "consents.instances.sign_professional": "Registrar firma profesional",
  "consents.instances.sign_representative": "Registrar firma del representante",
  "consents.instances.finalize": "Finalizar consentimientos",
  "consents.instances.void": "Anular consentimientos",
  "consents.instances.download": "Descargar consentimiento final",
  "consents.instances.view_evidence": "Consultar evidencia de consentimiento",
  "reports.read": "Ver reportes",
  "reports.export": "Exportar reportes",
  "integrations.communications.read": "Ver comunicaciones CRM",
  "integrations.communications.send": "Enviar comunicaciones CRM",
  "integrations.surveys.read": "Ver encuestas y NPS",
  "integrations.surveys.manage": "Administrar encuestas",
  "integrations.chat.read": "Ver chat interno",
  "integrations.chat.send": "Enviar mensajes de chat",
  "integrations.telemedicine.read": "Ver telemedicina",
  "integrations.telemedicine.manage": "Administrar telemedicina",
  "integrations.imports.read": "Ver importaciones",
  "integrations.imports.manage": "Administrar importaciones",
  "integrations.ai.read": "Ver solicitudes IA",
  "integrations.ai.request": "Crear solicitudes IA",
  "integrations.ai.complete": "Completar solicitudes IA",
  "document_requirements.read": "Ver requisitos documentales",
  "document_requirements.manage": "Administrar requisitos documentales",
  "document_requirements.satisfy": "Marcar requisitos cumplidos",
  "document_requirements.waive": "Eximir requisitos documentales",
  "payment_webhooks.read": "Ver webhooks de pago",
  "payment_webhooks.manage": "Administrar webhooks de pago",
  "lab_providers.read": "Ver laboratorios",
  "lab_providers.create": "Crear laboratorios",
  "lab_providers.update": "Editar laboratorios",
  "lab_providers.deactivate": "Desactivar laboratorios",
  "lab_orders.read": "Ver ordenes de laboratorio",
  "lab_orders.create": "Crear ordenes de laboratorio",
  "lab_orders.update": "Editar ordenes de laboratorio",
  "lab_orders.cost.update": "Editar costo de ordenes de laboratorio",
  "lab_profitability.read": "Ver rentabilidad de laboratorio",
  "suppliers.read": "Ver proveedores",
  "suppliers.create": "Crear proveedores",
  "suppliers.update": "Editar proveedores",
  "suppliers.deactivate": "Desactivar proveedores",
  "inventory.read": "Ver inventario",
  "inventory.create": "Crear articulos de inventario",
  "inventory.update": "Editar inventario",
  "inventory.deactivate": "Desactivar articulos de inventario",
  "inventory.movements.read": "Ver movimientos de inventario",
  "inventory.movements.create": "Crear movimientos de inventario",
  "inventory.alerts.read": "Ver alertas de inventario",
  "inventory.warehouses.read": "Ver bodegas de inventario",
  "inventory.warehouses.manage": "Administrar bodegas de inventario",
  "inventory.reports.read": "Exportar reportes de inventario",
  "inventory.adjustments.create": "Crear ajustes de inventario",
  "inventory.sell": "Vender productos de inventario",
  "online_scheduling.read": "Ver agenda online",
  "online_scheduling.update": "Editar agenda online",
  "treatment_plans.duplicate": "Duplicar planes de tratamiento",
  "treatment_plans.reactivate": "Reactivar planes de tratamiento",
  "treatment_plans.derive": "Derivar planes de tratamiento",
  "clinical.documents.delete": "Eliminar documentos clinicos",
  "clinical.files.delete": "Eliminar archivos clinicos",
  "rx_analysis.run": "Ejecutar analisis RX",
  "collections.payroll_discounts.manage": "Administrar descuentos por nomina",
  "reports.collections.read": "Ver reportes de cobranza"
};

export const PERMISSION_DESCRIPTIONS: Record<string, string> = {
  "system.manage_all": "Permite administrar toda la plataforma sin restricciones de permisos.",
  "dashboard.read": "Permite visualizar el panel principal.",
  "users.read": "Permite consultar usuarios y colaboradores.",
  "users.create": "Permite crear nuevos usuarios y colaboradores.",
  "users.update": "Permite editar datos, acceso, rol y estado operativo de usuarios.",
  "users.deactivate": "Permite desactivar usuarios.",
  "roles.read": "Permite consultar perfiles y sus permisos.",
  "roles.create": "Permite crear perfiles con permisos asignados.",
  "roles.update": "Permite editar perfiles y sus permisos.",
  "roles.deactivate": "Permite desactivar perfiles que no esten asignados a usuarios activos.",
  "permissions.read": "Permite consultar el catalogo de permisos.",
  "permissions.create": "Permite crear permisos del sistema.",
  "permissions.update": "Permite editar permisos del sistema.",
  "permissions.deactivate": "Permite desactivar permisos no protegidos del sistema.",
  "branches.read": "Permite consultar sucursales.",
  "branches.create": "Permite crear sucursales.",
  "branches.update": "Permite editar sucursales.",
  "branches.deactivate": "Permite desactivar sucursales.",
  "branches.archive": "Permite archivar sucursales sin borrar su historial.",
  "branches.restore": "Permite restaurar sucursales archivadas.",
  "branches.assign_brand": "Permite mover sucursales entre marcas de la misma organizacion.",
  "branches.manage_contact": "Permite editar datos de contacto y configuracion publica de sucursales.",
  "branches.view_all": "Permite consultar todas las sucursales de la organizacion.",
  "health_center.view": "Permite consultar el modulo Mi centro de salud.",
  "health_center.manage": "Permite administrar marcas y sucursales desde Mi centro de salud.",
  "brands.view": "Permite consultar marcas comerciales.",
  "brands.create": "Permite crear marcas comerciales.",
  "brands.update": "Permite editar marcas comerciales.",
  "brands.archive": "Permite archivar marcas comerciales sin borrar datos.",
  "brands.manage_identity": "Permite editar logotipo, colores y presencia publica de marca.",
  "brands.manage_communications": "Permite editar remitentes, reply-to y dominios de marca.",
  "users.manage_branch_access": "Permite asignar o retirar acceso de usuarios a sucursales.",
  "settings.read": "Permite consultar configuraciones administrativas.",
  "settings.update": "Permite modificar configuraciones administrativas.",
  "specialties.read": "Permite consultar especialidades.",
  "specialties.create": "Permite crear especialidades.",
  "specialties.update": "Permite editar especialidades y sus reglas.",
  "specialties.deactivate": "Permite desactivar especialidades.",
  "professionals.read": "Permite consultar profesionales.",
  "professionals.create": "Permite crear profesionales.",
  "professionals.update": "Permite editar profesionales, agenda y configuracion asociada.",
  "professionals.deactivate": "Permite desactivar profesionales.",
  "schedules.read": "Permite consultar horarios de profesionales.",
  "schedules.create": "Permite crear horarios.",
  "schedules.update": "Permite editar horarios.",
  "schedules.deactivate": "Permite desactivar horarios.",
  "chairs.read": "Permite consultar sillones o cubiculos.",
  "chairs.create": "Permite crear sillones o cubiculos.",
  "chairs.update": "Permite editar sillones o cubiculos.",
  "chairs.deactivate": "Permite desactivar sillones o cubiculos.",
  "payment_methods.read": "Permite consultar metodos de pago.",
  "payment_methods.create": "Permite crear metodos de pago.",
  "payment_methods.update": "Permite editar metodos de pago.",
  "payment_methods.deactivate": "Permite desactivar metodos de pago.",
  "payment_methods.reactivate": "Permite reactivar medios deshabilitados sin perder historial.",
  "payment_methods.configure_retention": "Permite configurar el porcentaje retenido por cada medio.",
  "payment_methods.configure_refunds": "Permite decidir si un medio puede usarse en devoluciones.",
  "payment_methods.configure_multiple_settlements":
    "Permite programar varias recepciones bancarias de un mismo cobro.",
  "payment_methods.configure_cash_impact": "Permite cambiar cómo el medio afecta caja, cierres y reportes.",
  "payment_methods.view_audit": "Permite consultar cambios históricos de medios de pago.",
  "payment_settlements.read": "Permite consultar vencimientos y recepciones programadas.",
  "payment_settlements.receive": "Permite confirmar un vencimiento como recibido en caja.",
  "payment_settlements.cancel": "Permite cancelar un vencimiento pendiente con motivo y auditoría.",
  "payment_options.cash_discounts.view": "Permite consultar reglas y vigencias de descuentos por caja.",
  "payment_options.cash_discounts.create": "Permite crear promociones de liquidacion en caja.",
  "payment_options.cash_discounts.update": "Permite editar reglas de descuentos por caja con versionado.",
  "payment_options.cash_discounts.disable": "Permite deshabilitar promociones sin borrar su historial.",
  "payment_options.cash_discounts.reactivate": "Permite reactivar promociones deshabilitadas.",
  "payments.cash_discounts.apply": "Permite aplicar una promocion autorizada al liquidar prestaciones.",
  "payments.cash_discounts.override": "Permiso reservado para excepciones; no se asigna por defecto.",
  "payments.cash_discounts.view_audit":
    "Permite consultar aplicaciones, rechazos, anulaciones y devoluciones.",
  "procedure_categories.read": "Permite consultar categorias de procedimientos.",
  "procedure_categories.create": "Permite crear categorias de procedimientos.",
  "procedure_categories.update": "Permite editar categorias de procedimientos.",
  "procedure_categories.deactivate": "Permite desactivar categorias de procedimientos.",
  "procedures.read": "Permite consultar procedimientos.",
  "procedures.create": "Permite crear procedimientos.",
  "procedures.update": "Permite editar procedimientos.",
  "procedures.deactivate": "Permite desactivar procedimientos.",
  "price_lists.read": "Permite consultar listas de precios.",
  "price_lists.create": "Permite crear listas de precios.",
  "price_lists.update": "Permite editar listas de precios y asignaciones por sucursal.",
  "price_lists.configure_discount_limits":
    "Permite configurar si una prestación admite descuento y su porcentaje máximo.",
  "price_lists.override_manual": "Permite registrar precios manuales distintos al arancel resuelto.",
  "price_lists.deactivate": "Permite desactivar listas de precios.",
  "treatment_discount.apply": "Permite aplicar descuentos solo sobre prestaciones elegibles.",
  "treatment_discount.configure_user_limits":
    "Permite configurar el porcentaje máximo de descuento autorizado para cada usuario.",
  "treatment_discount.override": "Permite autorizar descuentos que superan umbrales definidos.",
  "treatment_discount.view": "Permite ver detalle de descuentos aplicados.",
  "treatment_discount.audit": "Permite revisar auditoria de descuentos.",
  "patients.read": "Permite consultar pacientes.",
  "patient_analytics.read": "Permite consultar indicadores agregados del modulo Pacientes.",
  "patient_analytics.read_financial":
    "Permite recibir deuda, pagos e importes de presupuestos en el analisis.",
  "patient_analytics.view_all_branches":
    "Permite consolidar en una consulta todas las sucursales autorizadas.",
  "patient_analytics.export": "Permite exportar detalles autorizados del analisis.",
  "patient_analytics.refresh": "Permite solicitar un calculo actualizado de indicadores.",
  "patient_analytics.view_patient_details":
    "Permite identificar pacientes y abrir su ficha desde el detalle analitico.",
  "patients.create": "Permite crear pacientes.",
  "patients.update": "Permite editar datos del paciente.",
  "patient_identity.config.read": "Permite consultar las reglas y banderas de identidad.",
  "patient_identity.config.manage":
    "Permite activar gradualmente resolución de identidad y grupos familiares.",
  "contact_points.read": "Permite consultar teléfonos normalizados y sus relaciones.",
  "contact_points.link": "Permite vincular un teléfono personal o compartido.",
  "contact_points.verify": "Permite registrar verificación de control del canal.",
  "contact_points.transfer": "Permite transferir vínculos telefónicos con auditoría.",
  "contact_points.backfill": "Permite migrar teléfonos heredados al modelo de contactos.",
  "family_groups.read": "Permite consultar grupos familiares sin otorgar acceso clínico.",
  "family_groups.create": "Permite crear grupos familiares.",
  "family_groups.manage_members": "Permite gestionar integrantes, roles y consentimientos.",
  "family_groups.manage_contacts": "Permite administrar teléfonos compartidos del grupo.",
  "family_groups.manage_permissions":
    "Permite administrar permisos granulares de agenda, recordatorios y acceso sensible por integrante.",
  "patient_duplicates.review": "Permite revisar candidatos antes de crear o fusionar fichas.",
  "patients.merge": "Permite ejecutar una fusión auditada después de revisar su impacto.",
  "booking_identity.review": "Permite revisar sesiones ambiguas del bot o Agenda Online.",
  "booking_identity.resolve": "Permite resolver manualmente una identidad de reserva.",
  "patients.deactivate": "Permite desactivar pacientes.",
  "patients.notes.create": "Permite crear notas administrativas o clinicas del paciente.",
  "patients.alerts.create": "Permite crear alertas del paciente.",
  "patients.tasks.read": "Permite consultar tareas de gestion del paciente.",
  "patients.tasks.create": "Permite crear tareas de gestion del paciente.",
  "patients.tasks.update": "Permite editar responsable, vencimiento y detalle de tareas del paciente.",
  "patients.tasks.complete": "Permite finalizar tareas de gestion del paciente.",
  "appointments.read": "Permite consultar citas y agenda.",
  "appointments.create": "Permite crear citas.",
  "appointments.update": "Permite editar citas y notas asociadas.",
  "appointments.cancel": "Permite cancelar citas.",
  "appointments.status.update": "Permite cambiar el estado de citas.",
  "appointments.overbook": "Permite crear citas aunque no haya disponibilidad normal.",
  "appointments.block": "Permite bloquear espacios de agenda.",
  "clinical.read": "Permite consultar el expediente clinico.",
  "clinical.history.update": "Permite editar historia clinica y antecedentes.",
  "clinical.evolutions.create": "Permite crear evoluciones clinicas.",
  "clinical.evolutions.sign": "Permite firmar evoluciones clinicas.",
  "clinical.prescriptions.create": "Permite crear recetas.",
  "clinical.documents.create": "Permite crear documentos clinicos.",
  "clinical.templates.manage": "Permite administrar plantillas de documentos clinicos.",
  "clinical.odontogram.read": "Permite consultar odontograma e historial dental.",
  "clinical.odontogram.write": "Permite crear y editar registros del odontograma.",
  "clinical.periodontogram.read": "Permite consultar periodontogramas y comparativos.",
  "clinical.periodontogram.write": "Permite crear registros de periodontograma.",
  "treatment_plans.read": "Permite consultar planes de tratamiento.",
  "treatment_plans.create": "Permite crear planes de tratamiento.",
  "treatment_plans.update": "Permite editar planes de tratamiento.",
  "treatment_plans.status.update": "Permite actualizar estados de tratamientos o prestaciones.",
  "treatment_plans.alternatives.manage": "Permite administrar alternativas de tratamiento.",
  "orthodontic_catalogs.manage":
    "Permite crear, desactivar, reactivar y ordenar opciones tecnicas de ortodoncia.",
  "orthodontic_diagnosis.read": "Permite consultar diagnosticos de ortodoncia.",
  "orthodontic_diagnosis.create": "Permite guardar diagnosticos activos de ortodoncia.",
  "orthodontic_diagnosis.draft": "Permite guardar borradores de diagnostico de ortodoncia.",
  "orthodontic_diagnosis.update": "Permite crear nuevas versiones de diagnosticos activos.",
  "orthodontic_diagnosis.history.read": "Permite consultar versiones anteriores del diagnostico.",
  "orthodontic_diagnosis.catalogs.manage":
    "Permite crear, desactivar, reactivar y ordenar opciones del catalogo de diagnostico.",
  "budgets.read": "Permite consultar presupuestos.",
  "budgets.create": "Permite generar presupuestos.",
  "budgets.update": "Permite editar presupuestos.",
  "budgets.send": "Permite enviar presupuestos a pacientes.",
  "budgets.accept": "Permite aceptar presupuestos y tratamientos.",
  "budgets.reject": "Permite rechazar presupuestos.",
  "budgets.print": "Permite imprimir presupuestos.",
  "payments.read": "Permite consultar pagos y cobranza.",
  "payments.create": "Permite registrar pagos de pacientes.",
  "payments.update": "Permite modificar metadatos de pagos sin alterar montos.",
  "payments.allocate": "Permite asignar pagos a tratamientos o cuotas.",
  "payments.refund": "Permite registrar devoluciones o reembolsos.",
  "payments.override.closed_cash": "Permite recibir pagos sin caja abierta.",
  "payment_links.create": "Permite generar enlaces de pago.",
  "installments.read": "Permite consultar planes de cuotas y cuotas.",
  "installments.create": "Permite crear planes de cuotas.",
  "installments.pay": "Permite registrar pagos de cuotas.",
  "cash_register.read": "Permite consultar turnos y saldos de caja.",
  "cash_register.open": "Permite abrir caja.",
  "cash_register.close": "Permite cerrar caja.",
  "cash_register.close_any": "Permite cerrar cajas abiertas por otro usuario.",
  "cash_register.move": "Permite registrar movimientos manuales de caja.",
  "expenses.read": "Permite consultar gastos administrativos y operativos.",
  "expenses.create": "Permite registrar gastos y asignarlos a una caja abierta.",
  "expenses.update": "Permite corregir gastos mientras su caja asociada siga abierta.",
  "expenses.void": "Permite anular gastos conservando historial y contramovimientos.",
  "accounts_receivable.read": "Permite consultar saldos pendientes y cuotas vencidas.",
  "collections.read": "Permite consultar casos de cobranza.",
  "collections.create": "Permite crear casos de cobranza.",
  "collections.detect": "Permite detectar cuotas vencidas y crear casos.",
  "collections.update": "Permite editar estado y asignacion de casos de cobranza.",
  "collections.activities.create": "Permite registrar llamadas, mensajes y actividades de cobranza.",
  "files.read": "Permite consultar archivos y adjuntos de pacientes.",
  "files.upload": "Permite subir archivos y adjuntos.",
  "patients.files.manage": "Permite eliminar archivos adjuntos de pacientes con trazabilidad.",
  "consent_templates.read": "Permite consultar plantillas de consentimiento.",
  "consent_templates.create": "Permite crear plantillas de consentimiento.",
  "consent_templates.update": "Permite editar plantillas de consentimiento.",
  "consent_templates.deactivate": "Permite desactivar plantillas de consentimiento.",
  "consents.read": "Permite consultar consentimientos generados.",
  "consents.create": "Permite generar consentimientos para pacientes.",
  "consents.sign": "Permite firmar y bloquear consentimientos.",
  "consents.pdf": "Permite descargar el PDF del consentimiento firmado.",
  "reports.read": "Permite consultar dashboards y reportes.",
  "reports.export": "Permite exportar reportes en archivos.",
  "integrations.communications.read":
    "Permite consultar trabajos de comunicacion por email, WhatsApp y canales internos.",
  "integrations.communications.send": "Permite crear y encolar comunicaciones para pacientes.",
  "integrations.surveys.read": "Permite consultar encuestas y respuestas NPS.",
  "integrations.surveys.manage": "Permite crear, enviar y administrar encuestas.",
  "integrations.chat.read": "Permite consultar mensajes del chat interno.",
  "integrations.chat.send": "Permite enviar mensajes en el chat interno.",
  "integrations.telemedicine.read": "Permite consultar sesiones de telemedicina.",
  "integrations.telemedicine.manage": "Permite crear y actualizar sesiones de telemedicina.",
  "integrations.imports.read": "Permite consultar trabajos de importacion masiva.",
  "integrations.imports.manage": "Permite crear y actualizar trabajos de importacion masiva.",
  "integrations.ai.read": "Permite consultar solicitudes y resultados de IA.",
  "integrations.ai.request": "Permite crear solicitudes de analisis IA.",
  "integrations.ai.complete": "Permite registrar resultados devueltos por proveedores IA.",
  "document_requirements.read": "Permite consultar requisitos documentales clinicos.",
  "document_requirements.manage": "Permite crear y administrar requisitos documentales.",
  "document_requirements.satisfy": "Permite marcar requisitos documentales como cumplidos.",
  "document_requirements.waive": "Permite eximir requisitos documentales con motivo.",
  "payment_webhooks.read": "Permite consultar eventos recibidos desde proveedores de pago.",
  "payment_webhooks.manage": "Permite administrar eventos de webhooks de pago.",
  "lab_providers.read": "Permite consultar proveedores de laboratorio.",
  "lab_providers.create": "Permite crear proveedores de laboratorio.",
  "lab_providers.update": "Permite editar proveedores de laboratorio.",
  "lab_providers.deactivate": "Permite desactivar proveedores de laboratorio.",
  "lab_orders.read": "Permite consultar ordenes de laboratorio.",
  "lab_orders.create": "Permite crear ordenes de laboratorio.",
  "lab_orders.update": "Permite actualizar estado de ordenes de laboratorio.",
  "lab_orders.cost.update": "Permite editar costos de ordenes de laboratorio.",
  "lab_profitability.read": "Permite ver rentabilidad de tratamientos con costos de laboratorio.",
  "suppliers.read": "Permite consultar proveedores de inventario.",
  "suppliers.create": "Permite crear proveedores de inventario.",
  "suppliers.update": "Permite editar proveedores de inventario.",
  "suppliers.deactivate": "Permite desactivar proveedores de inventario.",
  "inventory.read": "Permite consultar articulos de inventario.",
  "inventory.create": "Permite crear articulos de inventario.",
  "inventory.update": "Permite editar articulos de inventario.",
  "inventory.deactivate": "Permite desactivar articulos de inventario.",
  "inventory.movements.read": "Permite consultar movimientos de inventario.",
  "inventory.movements.create": "Permite crear movimientos de inventario.",
  "inventory.alerts.read": "Permite consultar alertas de stock minimo.",
  "inventory.warehouses.read": "Permite consultar bodegas de inventario.",
  "inventory.warehouses.manage": "Permite crear y editar bodegas de inventario.",
  "inventory.reports.read": "Permite exportar reportes operativos de inventario.",
  "inventory.adjustments.create": "Permite crear ajustes de stock con trazabilidad.",
  "inventory.sell": "Permite registrar ventas de productos de inventario.",
  "online_scheduling.read": "Permite consultar configuracion de agenda online.",
  "online_scheduling.update": "Permite modificar configuracion de agenda online.",
  "treatment_plans.duplicate": "Permite duplicar planes de tratamiento existentes.",
  "treatment_plans.reactivate": "Permite reactivar planes de tratamiento cancelados.",
  "treatment_plans.derive": "Permite derivar planes de tratamiento entre profesionales o sucursales.",
  "clinical.documents.delete": "Permite eliminar logicamente documentos clinicos.",
  "clinical.files.delete": "Permite eliminar logicamente archivos clinicos.",
  "rx_analysis.run": "Permite ejecutar analisis IA sobre radiografias.",
  "collections.payroll_discounts.manage": "Permite administrar descuentos de nomina asociados a cobranza.",
  "reports.collections.read": "Permite consultar reportes de cobranza y morosidad."
};

export function getPermissionLabel(permission: PermissionListItem) {
  return (
    PERMISSION_LABELS[permission.key] ??
    permission.name ??
    permission.key ??
    permission.code ??
    permission.action
  );
}

export function getPermissionDescription(permission: PermissionListItem) {
  return PERMISSION_DESCRIPTIONS[permission.key] ?? permission.description;
}
