import type { PermissionListItem } from "./services/permissions.service";

export const PERMISSION_LABELS: Record<string, string> = {
  "system.manage_all": "Administrar todo",
  "dashboard.read": "Ver panel principal",
  "users.read": "Ver usuarios",
  "users.create": "Crear usuarios",
  "users.update": "Editar usuarios",
  "users.deactivate": "Desactivar usuarios",
  "roles.read": "Ver perfiles",
  "roles.create": "Crear perfiles",
  "roles.update": "Editar perfiles",
  "roles.deactivate": "Desactivar perfiles",
  "permissions.read": "Ver permisos",
  "permissions.create": "Crear permisos",
  "permissions.update": "Editar permisos",
  "permissions.deactivate": "Desactivar permisos",
  "branches.read": "Ver sucursales",
  "branches.create": "Crear sucursales",
  "branches.update": "Editar sucursales",
  "branches.deactivate": "Desactivar sucursales",
  "settings.read": "Ver configuracion",
  "settings.update": "Editar configuracion",
  "specialties.read": "Ver especialidades",
  "specialties.create": "Crear especialidades",
  "specialties.update": "Editar especialidades",
  "specialties.deactivate": "Desactivar especialidades",
  "professionals.read": "Ver profesionales",
  "professionals.create": "Crear profesionales",
  "professionals.update": "Editar profesionales",
  "professionals.deactivate": "Desactivar profesionales",
  "schedules.read": "Ver horarios",
  "schedules.create": "Crear horarios",
  "schedules.update": "Editar horarios",
  "schedules.deactivate": "Desactivar horarios",
  "chairs.read": "Ver sillones",
  "chairs.create": "Crear sillones",
  "chairs.update": "Editar sillones",
  "chairs.deactivate": "Desactivar sillones",
  "payment_methods.read": "Ver metodos de pago",
  "payment_methods.create": "Crear metodos de pago",
  "payment_methods.update": "Editar metodos de pago",
  "payment_methods.deactivate": "Desactivar metodos de pago",
  "procedure_categories.read": "Ver categorias de procedimientos",
  "procedure_categories.create": "Crear categorias de procedimientos",
  "procedure_categories.update": "Editar categorias de procedimientos",
  "procedure_categories.deactivate": "Desactivar categorias de procedimientos",
  "procedures.read": "Ver procedimientos",
  "procedures.create": "Crear procedimientos",
  "procedures.update": "Editar procedimientos",
  "procedures.deactivate": "Desactivar procedimientos",
  "price_lists.read": "Ver listas de precios",
  "price_lists.create": "Crear listas de precios",
  "price_lists.update": "Editar listas de precios",
  "price_lists.override_manual": "Sobrescribir precios manualmente",
  "price_lists.deactivate": "Desactivar listas de precios",
  "patients.read": "Ver pacientes",
  "patients.create": "Crear pacientes",
  "patients.update": "Editar pacientes",
  "patients.deactivate": "Desactivar pacientes",
  "patients.notes.create": "Crear notas de pacientes",
  "patients.alerts.create": "Crear alertas de pacientes",
  "patients.tasks.read": "Ver tareas de pacientes",
  "patients.tasks.create": "Crear tareas de pacientes",
  "patients.tasks.update": "Editar tareas de pacientes",
  "patients.tasks.complete": "Finalizar tareas de pacientes",
  "appointments.read": "Ver citas",
  "appointments.create": "Crear citas",
  "appointments.update": "Editar citas",
  "appointments.cancel": "Cancelar citas",
  "appointments.status.update": "Actualizar estado de citas",
  "appointments.overbook": "Agendar fuera de disponibilidad",
  "appointments.block": "Bloquear espacios de agenda",
  "clinical.read": "Ver expediente clinico",
  "clinical.history.update": "Editar historia clinica",
  "clinical.evolutions.create": "Crear evoluciones clinicas",
  "clinical.evolutions.sign": "Firmar evoluciones clinicas",
  "clinical.prescriptions.create": "Crear recetas",
  "clinical.documents.create": "Crear documentos clinicos",
  "clinical.templates.manage": "Administrar plantillas clinicas",
  "clinical.odontogram.read": "Ver odontograma",
  "clinical.odontogram.write": "Editar odontograma",
  "clinical.periodontogram.read": "Ver periodontograma",
  "clinical.periodontogram.write": "Crear periodontograma",
  "treatment_plans.read": "Ver planes de tratamiento",
  "treatment_plans.create": "Crear planes de tratamiento",
  "treatment_plans.update": "Editar planes de tratamiento",
  "treatment_plans.status.update": "Actualizar estado de tratamientos",
  "treatment_plans.alternatives.manage": "Administrar alternativas de tratamiento",
  "budgets.read": "Ver presupuestos",
  "budgets.create": "Crear presupuestos",
  "budgets.update": "Editar presupuestos",
  "budgets.send": "Enviar presupuestos",
  "budgets.accept": "Aceptar presupuestos",
  "budgets.reject": "Rechazar presupuestos",
  "budgets.print": "Imprimir presupuestos",
  "payments.read": "Ver pagos",
  "payments.create": "Registrar pagos",
  "payments.update": "Modificar pagos",
  "payments.allocate": "Asignar pagos",
  "payments.refund": "Registrar devoluciones",
  "payments.override.closed_cash": "Permitir pagos sin caja abierta",
  "payment_links.create": "Crear enlaces de pago",
  "installments.read": "Ver cuotas",
  "installments.create": "Crear cuotas",
  "installments.pay": "Registrar pago de cuotas",
  "cash_register.read": "Ver caja",
  "cash_register.open": "Abrir caja",
  "cash_register.close": "Cerrar caja",
  "cash_register.close_any": "Cerrar caja de otro usuario",
  "cash_register.move": "Registrar movimiento de caja",
  "accounts_receivable.read": "Ver cuentas por cobrar",
  "collections.read": "Ver cobranza",
  "collections.create": "Crear casos de cobranza",
  "collections.detect": "Detectar cuentas vencidas",
  "collections.update": "Editar cobranza",
  "collections.activities.create": "Crear actividades de cobranza",
  "files.read": "Ver archivos",
  "files.upload": "Subir archivos",
  "consent_templates.read": "Ver plantillas de consentimiento",
  "consent_templates.create": "Crear plantillas de consentimiento",
  "consent_templates.update": "Editar plantillas de consentimiento",
  "consent_templates.deactivate": "Desactivar plantillas de consentimiento",
  "consents.read": "Ver consentimientos",
  "consents.create": "Crear consentimientos",
  "consents.sign": "Firmar consentimientos",
  "consents.pdf": "Descargar PDF de consentimiento",
  "reports.read": "Ver reportes",
  "reports.export": "Exportar reportes",
  "lab_providers.read": "Ver laboratorios",
  "lab_providers.create": "Crear laboratorios",
  "lab_providers.update": "Editar laboratorios",
  "lab_providers.deactivate": "Desactivar laboratorios",
  "lab_orders.read": "Ver ordenes de laboratorio",
  "lab_orders.create": "Crear ordenes de laboratorio",
  "lab_orders.update": "Editar ordenes de laboratorio",
  "lab_orders.cost.update": "Editar costo de ordenes de laboratorio",
  "lab_profitability.read": "Ver rentabilidad de laboratorio",
  "suppliers.read": "Ver proveedores",
  "suppliers.create": "Crear proveedores",
  "suppliers.update": "Editar proveedores",
  "suppliers.deactivate": "Desactivar proveedores",
  "inventory.read": "Ver inventario",
  "inventory.create": "Crear articulos de inventario",
  "inventory.update": "Editar inventario",
  "inventory.deactivate": "Desactivar articulos de inventario",
  "inventory.movements.read": "Ver movimientos de inventario",
  "inventory.movements.create": "Crear movimientos de inventario",
  "inventory.alerts.read": "Ver alertas de inventario",
  "inventory.warehouses.read": "Ver bodegas de inventario",
  "inventory.warehouses.manage": "Administrar bodegas de inventario",
  "inventory.reports.read": "Exportar reportes de inventario",
  "inventory.adjustments.create": "Crear ajustes de inventario",
  "inventory.sell": "Vender productos de inventario"
};

export const PERMISSION_DESCRIPTIONS: Record<string, string> = {
  "system.manage_all": "Permite administrar toda la plataforma sin restricciones de permisos.",
  "dashboard.read": "Permite visualizar el panel principal.",
  "users.read": "Permite consultar usuarios y colaboradores.",
  "users.create": "Permite crear nuevos usuarios y colaboradores.",
  "users.update": "Permite editar datos, acceso, rol y estado operativo de usuarios.",
  "users.deactivate": "Permite desactivar usuarios.",
  "roles.read": "Permite consultar perfiles y sus permisos.",
  "roles.create": "Permite crear perfiles con permisos asignados.",
  "roles.update": "Permite editar perfiles y sus permisos.",
  "roles.deactivate": "Permite desactivar perfiles que no esten asignados a usuarios activos.",
  "permissions.read": "Permite consultar el catalogo de permisos.",
  "permissions.create": "Permite crear permisos del sistema.",
  "permissions.update": "Permite editar permisos del sistema.",
  "permissions.deactivate": "Permite desactivar permisos no protegidos del sistema.",
  "branches.read": "Permite consultar sucursales.",
  "branches.create": "Permite crear sucursales.",
  "branches.update": "Permite editar sucursales.",
  "branches.deactivate": "Permite desactivar sucursales.",
  "settings.read": "Permite consultar configuraciones administrativas.",
  "settings.update": "Permite modificar configuraciones administrativas.",
  "specialties.read": "Permite consultar especialidades.",
  "specialties.create": "Permite crear especialidades.",
  "specialties.update": "Permite editar especialidades y sus reglas.",
  "specialties.deactivate": "Permite desactivar especialidades.",
  "professionals.read": "Permite consultar profesionales.",
  "professionals.create": "Permite crear profesionales.",
  "professionals.update": "Permite editar profesionales, agenda y configuracion asociada.",
  "professionals.deactivate": "Permite desactivar profesionales.",
  "schedules.read": "Permite consultar horarios de profesionales.",
  "schedules.create": "Permite crear horarios.",
  "schedules.update": "Permite editar horarios.",
  "schedules.deactivate": "Permite desactivar horarios.",
  "chairs.read": "Permite consultar sillones o cubiculos.",
  "chairs.create": "Permite crear sillones o cubiculos.",
  "chairs.update": "Permite editar sillones o cubiculos.",
  "chairs.deactivate": "Permite desactivar sillones o cubiculos.",
  "payment_methods.read": "Permite consultar metodos de pago.",
  "payment_methods.create": "Permite crear metodos de pago.",
  "payment_methods.update": "Permite editar metodos de pago.",
  "payment_methods.deactivate": "Permite desactivar metodos de pago.",
  "procedure_categories.read": "Permite consultar categorias de procedimientos.",
  "procedure_categories.create": "Permite crear categorias de procedimientos.",
  "procedure_categories.update": "Permite editar categorias de procedimientos.",
  "procedure_categories.deactivate": "Permite desactivar categorias de procedimientos.",
  "procedures.read": "Permite consultar procedimientos.",
  "procedures.create": "Permite crear procedimientos.",
  "procedures.update": "Permite editar procedimientos.",
  "procedures.deactivate": "Permite desactivar procedimientos.",
  "price_lists.read": "Permite consultar listas de precios.",
  "price_lists.create": "Permite crear listas de precios.",
  "price_lists.update": "Permite editar listas de precios y asignaciones por sucursal.",
  "price_lists.override_manual": "Permite registrar precios manuales distintos al arancel resuelto.",
  "price_lists.deactivate": "Permite desactivar listas de precios.",
  "patients.read": "Permite consultar pacientes.",
  "patients.create": "Permite crear pacientes.",
  "patients.update": "Permite editar datos del paciente.",
  "patients.deactivate": "Permite desactivar pacientes.",
  "patients.notes.create": "Permite crear notas administrativas o clinicas del paciente.",
  "patients.alerts.create": "Permite crear alertas del paciente.",
  "patients.tasks.read": "Permite consultar tareas de gestion del paciente.",
  "patients.tasks.create": "Permite crear tareas de gestion del paciente.",
  "patients.tasks.update": "Permite editar responsable, vencimiento y detalle de tareas del paciente.",
  "patients.tasks.complete": "Permite finalizar tareas de gestion del paciente.",
  "appointments.read": "Permite consultar citas y agenda.",
  "appointments.create": "Permite crear citas.",
  "appointments.update": "Permite editar citas y notas asociadas.",
  "appointments.cancel": "Permite cancelar citas.",
  "appointments.status.update": "Permite cambiar el estado de citas.",
  "appointments.overbook": "Permite crear citas aunque no haya disponibilidad normal.",
  "appointments.block": "Permite bloquear espacios de agenda.",
  "clinical.read": "Permite consultar el expediente clinico.",
  "clinical.history.update": "Permite editar historia clinica y antecedentes.",
  "clinical.evolutions.create": "Permite crear evoluciones clinicas.",
  "clinical.evolutions.sign": "Permite firmar evoluciones clinicas.",
  "clinical.prescriptions.create": "Permite crear recetas.",
  "clinical.documents.create": "Permite crear documentos clinicos.",
  "clinical.templates.manage": "Permite administrar plantillas de documentos clinicos.",
  "clinical.odontogram.read": "Permite consultar odontograma e historial dental.",
  "clinical.odontogram.write": "Permite crear y editar registros del odontograma.",
  "clinical.periodontogram.read": "Permite consultar periodontogramas y comparativos.",
  "clinical.periodontogram.write": "Permite crear registros de periodontograma.",
  "treatment_plans.read": "Permite consultar planes de tratamiento.",
  "treatment_plans.create": "Permite crear planes de tratamiento.",
  "treatment_plans.update": "Permite editar planes de tratamiento.",
  "treatment_plans.status.update": "Permite actualizar estados de tratamientos o prestaciones.",
  "treatment_plans.alternatives.manage": "Permite administrar alternativas de tratamiento.",
  "budgets.read": "Permite consultar presupuestos.",
  "budgets.create": "Permite generar presupuestos.",
  "budgets.update": "Permite editar presupuestos.",
  "budgets.send": "Permite enviar presupuestos a pacientes.",
  "budgets.accept": "Permite aceptar presupuestos y tratamientos.",
  "budgets.reject": "Permite rechazar presupuestos.",
  "budgets.print": "Permite imprimir presupuestos.",
  "payments.read": "Permite consultar pagos y cobranza.",
  "payments.create": "Permite registrar pagos de pacientes.",
  "payments.update": "Permite modificar metadatos de pagos sin alterar montos.",
  "payments.allocate": "Permite asignar pagos a tratamientos o cuotas.",
  "payments.refund": "Permite registrar devoluciones o reembolsos.",
  "payments.override.closed_cash": "Permite recibir pagos sin caja abierta.",
  "payment_links.create": "Permite generar enlaces de pago.",
  "installments.read": "Permite consultar planes de cuotas y cuotas.",
  "installments.create": "Permite crear planes de cuotas.",
  "installments.pay": "Permite registrar pagos de cuotas.",
  "cash_register.read": "Permite consultar turnos y saldos de caja.",
  "cash_register.open": "Permite abrir caja.",
  "cash_register.close": "Permite cerrar caja.",
  "cash_register.close_any": "Permite cerrar cajas abiertas por otro usuario.",
  "cash_register.move": "Permite registrar movimientos manuales de caja.",
  "accounts_receivable.read": "Permite consultar saldos pendientes y cuotas vencidas.",
  "collections.read": "Permite consultar casos de cobranza.",
  "collections.create": "Permite crear casos de cobranza.",
  "collections.detect": "Permite detectar cuotas vencidas y crear casos.",
  "collections.update": "Permite editar estado y asignacion de casos de cobranza.",
  "collections.activities.create": "Permite registrar llamadas, mensajes y actividades de cobranza.",
  "files.read": "Permite consultar archivos y adjuntos de pacientes.",
  "files.upload": "Permite subir archivos y adjuntos.",
  "consent_templates.read": "Permite consultar plantillas de consentimiento.",
  "consent_templates.create": "Permite crear plantillas de consentimiento.",
  "consent_templates.update": "Permite editar plantillas de consentimiento.",
  "consent_templates.deactivate": "Permite desactivar plantillas de consentimiento.",
  "consents.read": "Permite consultar consentimientos generados.",
  "consents.create": "Permite generar consentimientos para pacientes.",
  "consents.sign": "Permite firmar y bloquear consentimientos.",
  "consents.pdf": "Permite descargar el PDF del consentimiento firmado.",
  "reports.read": "Permite consultar dashboards y reportes.",
  "reports.export": "Permite exportar reportes en archivos.",
  "lab_providers.read": "Permite consultar proveedores de laboratorio.",
  "lab_providers.create": "Permite crear proveedores de laboratorio.",
  "lab_providers.update": "Permite editar proveedores de laboratorio.",
  "lab_providers.deactivate": "Permite desactivar proveedores de laboratorio.",
  "lab_orders.read": "Permite consultar ordenes de laboratorio.",
  "lab_orders.create": "Permite crear ordenes de laboratorio.",
  "lab_orders.update": "Permite actualizar estado de ordenes de laboratorio.",
  "lab_orders.cost.update": "Permite editar costos de ordenes de laboratorio.",
  "lab_profitability.read": "Permite ver rentabilidad de tratamientos con costos de laboratorio.",
  "suppliers.read": "Permite consultar proveedores de inventario.",
  "suppliers.create": "Permite crear proveedores de inventario.",
  "suppliers.update": "Permite editar proveedores de inventario.",
  "suppliers.deactivate": "Permite desactivar proveedores de inventario.",
  "inventory.read": "Permite consultar articulos de inventario.",
  "inventory.create": "Permite crear articulos de inventario.",
  "inventory.update": "Permite editar articulos de inventario.",
  "inventory.deactivate": "Permite desactivar articulos de inventario.",
  "inventory.movements.read": "Permite consultar movimientos de inventario.",
  "inventory.movements.create": "Permite crear movimientos de inventario.",
  "inventory.alerts.read": "Permite consultar alertas de stock minimo.",
  "inventory.warehouses.read": "Permite consultar bodegas de inventario.",
  "inventory.warehouses.manage": "Permite crear y editar bodegas de inventario.",
  "inventory.reports.read": "Permite exportar reportes operativos de inventario.",
  "inventory.adjustments.create": "Permite crear ajustes de stock con trazabilidad.",
  "inventory.sell": "Permite registrar ventas de productos de inventario."
};

export function getPermissionLabel(permission: PermissionListItem) {
  return PERMISSION_LABELS[permission.key] ?? permission.name ?? permission.key ?? permission.code ?? permission.action;
}

export function getPermissionDescription(permission: PermissionListItem) {
  return PERMISSION_DESCRIPTIONS[permission.key] ?? permission.description;
}
