WITH permission_seed("key", "name", "description", "module") AS (
  VALUES
    ('system.manage_all', 'Manage all', 'Global administration', 'system'),
    ('dashboard.read', 'Read dashboard', 'View dashboard', 'dashboard'),
    ('users.read', 'Read users', 'View users', 'users'),
    ('users.create', 'Create users', 'Create users', 'users'),
    ('users.update', 'Update users', 'Update users', 'users'),
    ('users.deactivate', 'Deactivate users', 'Deactivate users', 'users'),
    ('roles.read', 'Read roles', 'View roles', 'roles'),
    ('roles.create', 'Create roles', 'Create roles', 'roles'),
    ('roles.update', 'Update roles', 'Update roles', 'roles'),
    ('roles.deactivate', 'Deactivate roles', 'Deactivate roles', 'roles'),
    ('permissions.read', 'Read permissions', 'View permissions', 'permissions'),
    ('permissions.create', 'Create permissions', 'Create permissions', 'permissions'),
    ('permissions.update', 'Update permissions', 'Update permissions', 'permissions'),
    ('permissions.deactivate', 'Deactivate permissions', 'Deactivate permissions', 'permissions'),
    ('branches.read', 'Read branches', 'View branches', 'branches'),
    ('branches.create', 'Create branches', 'Create branches', 'branches'),
    ('branches.update', 'Update branches', 'Update branches', 'branches'),
    ('branches.deactivate', 'Deactivate branches', 'Deactivate branches', 'branches'),
    ('branches.archive', 'Archive branches', 'Archive branches', 'branches'),
    ('branches.restore', 'Restore branches', 'Restore archived branches', 'branches'),
    ('branches.assign_brand', 'Assign branch brand', 'Move branches between brands', 'branches'),
    ('branches.manage_contact', 'Manage branch contact', 'Update branch contact and public settings', 'branches'),
    ('branches.view_all', 'View all branches', 'View every branch in the organization', 'branches'),
    ('health_center.view', 'View health center', 'View organization brands and branches', 'health_center'),
    ('health_center.manage', 'Manage health center', 'Manage organization brands and branches', 'health_center'),
    ('brands.view', 'View brands', 'View commercial brands', 'brands'),
    ('brands.create', 'Create brands', 'Create commercial brands', 'brands'),
    ('brands.update', 'Update brands', 'Update commercial brands', 'brands'),
    ('brands.archive', 'Archive brands', 'Archive commercial brands', 'brands'),
    ('brands.manage_identity', 'Manage brand identity', 'Update logos, colors and public identity', 'brands'),
    ('brands.manage_communications', 'Manage brand communications', 'Update sender and reply-to settings', 'brands'),
    ('users.manage_branch_access', 'Manage branch access', 'Assign users to branches', 'users'),
    ('settings.read', 'Read settings', 'View settings', 'settings'),
    ('settings.update', 'Update settings', 'Update settings', 'settings'),
    ('agreements.read', 'Read agreements', 'View agreement pricing and versions', 'agreements'),
    ('agreements.manage', 'Manage agreements', 'Create drafts, versions and cancellations', 'agreements'),
    ('agreements.publish', 'Publish agreements', 'Activate or schedule agreement versions', 'agreements'),
    ('agreements.assign', 'Assign agreements', 'Assign active agreements to patients and treatment plans', 'agreements'),
    ('agreements.debt_report.read', 'Read agreement debt report', 'View company debt balances', 'agreements'),
    ('agreements.debt_report.all_branches', 'Read all agreement debt branches', 'View company debt across branches', 'agreements'),
    ('agreements.payments.create', 'Create company payments', 'Register company remittances', 'agreements'),
    ('agreements.payments.approve', 'Approve company payments', 'Confirm and allocate company remittances', 'agreements'),
    ('agreements.payments.void', 'Void company payments', 'Reverse company payments and allocations', 'agreements'),
    ('agreements.reports.export', 'Export agreement reports', 'Export agreement debt reports', 'agreements'),
    ('specialties.read', 'Read specialties', 'View specialties', 'specialties'),
    ('specialties.create', 'Create specialties', 'Create specialties', 'specialties'),
    ('specialties.update', 'Update specialties', 'Update specialties', 'specialties'),
    ('specialties.deactivate', 'Deactivate specialties', 'Deactivate specialties', 'specialties'),
    ('professionals.read', 'Read professionals', 'View professionals', 'professionals'),
    ('professionals.create', 'Create professionals', 'Create professionals', 'professionals'),
    ('professionals.update', 'Update professionals', 'Update professionals', 'professionals'),
    ('professionals.deactivate', 'Deactivate professionals', 'Deactivate professionals', 'professionals'),
    ('schedules.read', 'Read schedules', 'View schedules', 'schedules'),
    ('schedules.create', 'Create schedules', 'Create schedules', 'schedules'),
    ('schedules.update', 'Update schedules', 'Update schedules', 'schedules'),
    ('schedules.deactivate', 'Deactivate schedules', 'Deactivate schedules', 'schedules'),
    ('chairs.read', 'Read chairs', 'View chairs', 'chairs'),
    ('chairs.create', 'Create chairs', 'Create chairs', 'chairs'),
    ('chairs.update', 'Update chairs', 'Update chairs', 'chairs'),
    ('chairs.deactivate', 'Deactivate chairs', 'Deactivate chairs', 'chairs'),
    ('payment_methods.read', 'Read payment methods', 'View payment methods', 'payment_methods'),
    ('payment_methods.create', 'Create payment methods', 'Create payment methods', 'payment_methods'),
    ('payment_methods.update', 'Update payment methods', 'Update payment methods', 'payment_methods'),
    ('payment_methods.deactivate', 'Deactivate payment methods', 'Deactivate payment methods', 'payment_methods'),
    ('payment_methods.reactivate', 'Reactivate payment methods', 'Reactivate payment methods', 'payment_methods'),
    ('payment_methods.configure_retention', 'Configure payment retention', 'Configure retention percentage', 'payment_methods'),
    ('payment_methods.configure_refunds', 'Configure payment refunds', 'Configure refund eligibility', 'payment_methods'),
    ('payment_methods.configure_multiple_settlements', 'Configure multiple settlements', 'Configure scheduled receivables', 'payment_methods'),
    ('payment_methods.configure_cash_impact', 'Configure cash impact', 'Configure cash and reporting behavior', 'payment_methods'),
    ('payment_methods.view_audit', 'View payment method audit', 'View payment method history', 'payment_methods'),
    ('payment_settlements.read', 'Read payment settlements', 'View scheduled receivables', 'payment_methods'),
    ('payment_settlements.receive', 'Receive payment settlements', 'Mark scheduled receivables as received', 'payment_methods'),
    ('payment_settlements.cancel', 'Cancel payment settlements', 'Cancel pending scheduled receivables', 'payment_methods'),
    ('procedure_categories.read', 'Read procedure categories', 'View procedure categories', 'procedure_categories'),
    ('procedure_categories.create', 'Create procedure categories', 'Create procedure categories', 'procedure_categories'),
    ('procedure_categories.update', 'Update procedure categories', 'Update procedure categories', 'procedure_categories'),
    ('procedure_categories.deactivate', 'Deactivate procedure categories', 'Deactivate procedure categories', 'procedure_categories'),
    ('procedures.read', 'Read procedures', 'View procedures', 'procedures'),
    ('procedures.create', 'Create procedures', 'Create procedures', 'procedures'),
    ('procedures.update', 'Update procedures', 'Update procedures', 'procedures'),
    ('procedures.deactivate', 'Deactivate procedures', 'Deactivate procedures', 'procedures'),
    ('price_lists.read', 'Read price lists', 'View price lists', 'price_lists'),
    ('price_lists.create', 'Create price lists', 'Create price lists', 'price_lists'),
    ('price_lists.update', 'Update price lists', 'Update price lists', 'price_lists'),
    ('price_lists.configure_discount_limits', 'Configure procedure discount limits', 'Configure discount eligibility and maximum percentage by tariff item', 'price_lists'),
    ('price_lists.override_manual', 'Override price list prices', 'Allow manual treatment price overrides', 'price_lists'),
    ('price_lists.deactivate', 'Deactivate price lists', 'Deactivate price lists', 'price_lists'),
    ('treatment_discount.apply', 'Apply treatment discounts', 'Apply allowed treatment discounts', 'treatment_plans'),
    ('treatment_discount.configure_user_limits', 'Configure user discount limits', 'Configure the maximum treatment discount authorized for each user', 'treatment_plans'),
    ('treatment_discount.override', 'Override treatment discounts', 'Authorize treatment discounts over standard thresholds', 'treatment_plans'),
    ('treatment_discount.view', 'View treatment discounts', 'View treatment discount details', 'treatment_plans'),
    ('treatment_discount.audit', 'Audit treatment discounts', 'Review treatment discount audit trail', 'treatment_plans'),
    ('patients.read', 'Read patients', 'View patients', 'patients'),
    ('patient_analytics.read', 'Read patient analytics', 'View aggregate patient analytics', 'patients'),
    ('patient_analytics.read_financial', 'Read financial patient analytics', 'View debt, payment and monetary budget metrics', 'patients'),
    ('patient_analytics.view_all_branches', 'Consolidate patient analytics', 'View analytics across every authorized branch', 'patients'),
    ('patient_analytics.export', 'Export patient analytics', 'Export authorized analytics details', 'patients'),
    ('patient_analytics.refresh', 'Refresh patient analytics', 'Request a fresh analytics calculation', 'patients'),
    ('patient_analytics.view_patient_details', 'View patient analytics details', 'Open identified patient rows from analytics', 'patients'),
    ('patients.create', 'Create patients', 'Create patients', 'patients'),
    ('patients.update', 'Update patients', 'Update patients', 'patients'),
    ('patient_identity.config.read', 'Read patient identity configuration', 'View patient identity feature flags', 'patients'),
    ('patient_identity.config.manage', 'Manage patient identity configuration', 'Manage patient identity feature flags', 'patients'),
    ('contact_points.read', 'Read contact points', 'View normalized patient contact points', 'patients'),
    ('contact_points.link', 'Link contact points', 'Link shared or personal contact points', 'patients'),
    ('contact_points.verify', 'Verify contact points', 'Register contact point verification', 'patients'),
    ('contact_points.transfer', 'Transfer contact points', 'Transfer contact point ownership', 'patients'),
    ('contact_points.backfill', 'Backfill contact points', 'Migrate legacy patient phones', 'patients'),
    ('family_groups.read', 'Read family groups', 'View family groups', 'patients'),
    ('family_groups.create', 'Create family groups', 'Create family groups', 'patients'),
    ('family_groups.manage_members', 'Manage family members', 'Manage family group members', 'patients'),
    ('family_groups.manage_contacts', 'Manage family contacts', 'Manage family group contact points', 'patients'),
    ('family_groups.manage_permissions', 'Manage family permissions', 'Manage granular family booking, reminder, clinical and financial grants', 'patients'),
    ('family_policies.read', 'Read family policies', 'View family policy contracts', 'patients'),
    ('family_policies.create', 'Create family policies', 'Create family policy drafts', 'patients'),
    ('family_policies.manage', 'Manage family policies', 'Manage policy members and cancellations', 'patients'),
    ('family_policies.activate', 'Activate family policies', 'Register policy payments and activate coverage', 'patients'),
    ('family_policies.coverage.read', 'Read policy coverage', 'View policy coverage rules', 'patients'),
    ('family_policies.coverage.apply', 'Apply policy coverage', 'Apply coverage to treatments', 'patients'),
    ('family_policies.usage.read', 'Read policy usage', 'View policy usage history', 'patients'),
    ('patient_duplicates.review', 'Review patient duplicates', 'Review duplicate candidates', 'patients'),
    ('patients.merge', 'Merge patients', 'Execute audited patient merges', 'patients'),
    ('booking_identity.review', 'Review booking identity', 'Review ambiguous booking identity sessions', 'appointments'),
    ('booking_identity.resolve', 'Resolve booking identity', 'Resolve booking identity sessions manually', 'appointments'),
    ('patients.deactivate', 'Deactivate patients', 'Deactivate patients', 'patients'),
    ('patients.notes.create', 'Create patient notes', 'Create patient notes', 'patients'),
    ('patients.alerts.create', 'Create patient alerts', 'Create patient alerts', 'patients'),
    ('patients.tasks.read', 'Read patient tasks', 'View patient management tasks', 'patients'),
    ('patients.tasks.create', 'Create patient tasks', 'Create patient management tasks', 'patients'),
    ('patients.tasks.update', 'Update patient tasks', 'Update patient management tasks', 'patients'),
    ('patients.tasks.complete', 'Complete patient tasks', 'Complete patient management tasks', 'patients'),
    ('crm.tasks.read', 'View CRM tasks', 'View management tasks and history', 'crm'),
    ('crm.tasks.create', 'Create CRM tasks', 'Create manual management tasks', 'crm'),
    ('crm.tasks.update', 'Update CRM tasks', 'Edit and reassign management tasks', 'crm'),
    ('crm.tasks.complete', 'Complete CRM tasks', 'Complete management tasks', 'crm'),
    ('crm.tasks.reopen', 'Reopen CRM tasks', 'Reopen completed management tasks', 'crm'),
    ('crm.tasks.cancel', 'Cancel CRM tasks', 'Cancel management tasks with a reason', 'crm'),
    ('crm.tasks.statistics.read', 'View CRM task statistics', 'View aggregated management task statistics', 'crm'),
    ('crm.tasks.configuration.read', 'View CRM task configuration', 'View automatic task deadlines', 'crm'),
    ('crm.tasks.configuration.update', 'Update CRM task configuration', 'Update automatic task deadlines', 'crm'),
    ('appointments.read', 'Read appointments', 'View appointments', 'appointments'),
    ('appointments.create', 'Create appointments', 'Create appointments', 'appointments'),
    ('appointments.update', 'Update appointments', 'Update appointments', 'appointments'),
    ('appointments.cancel', 'Cancel appointments', 'Cancel appointments', 'appointments'),
    ('appointments.status.update', 'Update appointment status', 'Update appointment status', 'appointments'),
    ('appointments.overbook', 'Overbook appointments', 'Allow appointment overbooking', 'appointments'),
    ('appointments.block', 'Block appointment slots', 'Block appointment slots', 'appointments'),
    ('agenda.reprogramming.view', 'View appointment reprogramming', 'View pending reprogramming cases', 'appointments'),
    ('agenda.reprogramming.mass_cancel', 'Create reprogramming batches', 'Cancel appointments into a reprogramming queue', 'appointments'),
    ('agenda.reprogramming.reschedule', 'Reschedule pending cases', 'Create a replacement appointment from a pending case', 'appointments'),
    ('agenda.reprogramming.change_professional', 'Change reprogramming professional', 'Assign a different professional while rescheduling', 'appointments'),
    ('agenda.reprogramming.change_branch', 'Change reprogramming branch', 'Move a replacement appointment to another allowed branch', 'appointments'),
    ('agenda.reprogramming.definitive_cancel', 'Definitively cancel reprogramming cases', 'Close a case without creating a replacement appointment', 'appointments'),
    ('agenda.reprogramming.view_financial_status', 'View reprogramming financial status', 'View read-only treatment plan financial context', 'appointments'),
    ('agenda.reprogramming.view_audit', 'View reprogramming audit', 'View reprogramming batch and case audit history', 'appointments'),
    ('clinical.read', 'Read clinical record', 'View clinical record', 'clinical'),
    ('clinical.history.update', 'Update medical history', 'Update medical history', 'clinical'),
    ('clinical.evolutions.create', 'Create clinical evolutions', 'Create clinical evolutions', 'clinical'),
    ('clinical.evolutions.sign', 'Sign clinical evolutions', 'Sign clinical evolutions', 'clinical'),
    ('clinical.prescriptions.create', 'Create prescriptions', 'Create prescriptions', 'clinical'),
    ('clinical.documents.create', 'Create clinical documents', 'Create clinical documents', 'clinical'),
    ('clinical.templates.manage', 'Manage clinical templates', 'Manage clinical document templates', 'clinical'),
    ('clinical.odontogram.read', 'Read odontogram', 'View odontogram and tooth history', 'clinical'),
    ('clinical.odontogram.write', 'Write odontogram', 'Create and update odontogram records', 'clinical'),
    ('clinical.periodontogram.read', 'Read periodontogram', 'View periodontal charts and comparisons', 'clinical'),
    ('clinical.periodontogram.write', 'Write periodontogram', 'Create periodontal charts', 'clinical'),
    ('treatment_plans.read', 'Read treatment plans', 'View treatment plans', 'treatment_plans'),
    ('treatment_plans.create', 'Create treatment plans', 'Create treatment plans', 'treatment_plans'),
    ('treatment_plans.update', 'Update treatment plans', 'Update treatment plans', 'treatment_plans'),
    ('treatment_plans.status.update', 'Update treatment plan item status', 'Update treatment plan item status', 'treatment_plans'),
    ('treatment_plans.alternatives.manage', 'Manage treatment plan alternatives', 'Manage treatment plan alternatives', 'treatment_plans'),
    ('orthodontic_catalogs.manage', 'Manage orthodontic catalogs', 'Create, deactivate, reactivate and order orthodontic treatment catalog options', 'treatment_plans'),
    ('orthodontic_diagnosis.read', 'Read orthodontic diagnosis', 'View orthodontic diagnoses', 'treatment_plans'),
    ('orthodontic_diagnosis.create', 'Create orthodontic diagnosis', 'Save active orthodontic diagnoses', 'treatment_plans'),
    ('orthodontic_diagnosis.draft', 'Draft orthodontic diagnosis', 'Save orthodontic diagnosis drafts', 'treatment_plans'),
    ('orthodontic_diagnosis.update', 'Update orthodontic diagnosis', 'Create amended orthodontic diagnosis versions', 'treatment_plans'),
    ('orthodontic_diagnosis.history.read', 'Read orthodontic diagnosis history', 'View orthodontic diagnosis version history', 'treatment_plans'),
    ('orthodontic_diagnosis.catalogs.manage', 'Manage orthodontic diagnosis catalogs', 'Create, deactivate, reactivate and order orthodontic diagnosis options', 'treatment_plans'),
    ('budgets.read', 'Read budgets', 'View budgets', 'budgets'),
    ('budgets.create', 'Create budgets', 'Generate budgets', 'budgets'),
    ('budgets.update', 'Update budgets', 'Update budgets', 'budgets'),
    ('budgets.send', 'Send budgets', 'Send budgets to patients', 'budgets'),
    ('budgets.accept', 'Accept budgets', 'Accept budget and treatment plan', 'budgets'),
    ('budgets.reject', 'Reject budgets', 'Reject budget', 'budgets'),
    ('budgets.print', 'Print budgets', 'Print budget document', 'budgets'),
    ('print_complete_budget', 'Print complete budget', 'Print full treatment budget', 'documents'),
    ('print_total_only_budget', 'Print total-only budget', 'Print treatment budget with final total only', 'documents'),
    ('print_budget_without_values', 'Print budget without values', 'Print clinical treatment detail without economic values', 'documents'),
    ('print_care_plan', 'Print care plan', 'Print clinical care plan', 'documents'),
    ('print_treatment_sections', 'Print treatment sections', 'Print treatment plan sections', 'documents'),
    ('print_laboratory_order', 'Print laboratory order', 'Print linked laboratory orders', 'documents'),
    ('print_odontogram', 'Print odontogram', 'Print patient odontogram', 'documents'),
    ('print_clinical_history', 'Print clinical history', 'Print patient clinical history', 'documents'),
    ('select_print_logo', 'Select print logo', 'Select a logo for document generation', 'documents'),
    ('manage_logos', 'Manage logos', 'Create and deactivate document logos', 'documents'),
    ('assign_logos_to_branches', 'Assign logos to branches', 'Configure document logos by branch', 'documents'),
    ('view_generated_documents', 'View generated documents', 'View generated document history', 'documents'),
    ('void_generated_document', 'Void generated document', 'Void generated document records', 'documents'),
    ('payments.read', 'Read payments', 'View payments and collections', 'payments'),
    ('payments.create', 'Create payments', 'Register patient payments', 'payments'),
    ('payments.update', 'Update payments', 'Update payment metadata', 'payments'),
    ('payments.allocate', 'Allocate payments', 'Allocate payments to treatment items', 'payments'),
    ('payments.refund', 'Refund payments', 'Register payment refunds', 'payments'),
    ('payment_options.cash_discounts.view', 'View cash discounts', 'View cash discount configuration', 'payments'),
    ('payment_options.cash_discounts.create', 'Create cash discounts', 'Create cash discount rules', 'payments'),
    ('payment_options.cash_discounts.update', 'Update cash discounts', 'Edit cash discount rules', 'payments'),
    ('payment_options.cash_discounts.disable', 'Disable cash discounts', 'Disable cash discount rules without deleting history', 'payments'),
    ('payment_options.cash_discounts.reactivate', 'Reactivate cash discounts', 'Reactivate valid cash discount rules', 'payments'),
    ('payments.cash_discounts.apply', 'Apply cash discounts', 'Apply authorized cash discounts during full settlement', 'payments'),
    ('payments.cash_discounts.override', 'Override cash discounts', 'Reserved override permission; disabled by default', 'payments'),
    ('payments.cash_discounts.view_audit', 'View cash discount audit', 'View cash discount audit and historical applications', 'payments'),
    ('payments.override.closed_cash', 'Override closed cash register', 'Allow receiving payments without open cash register', 'payments'),
    ('payment_links.create', 'Create payment links', 'Create simulated online payment links', 'payments'),
    ('installments.read', 'Read installments', 'View installment plans and installments', 'installments'),
    ('installments.create', 'Create installments', 'Create installment plans', 'installments'),
    ('installments.pay', 'Pay installments', 'Register installment payments', 'installments'),
    ('cash_register.read', 'Read cash register', 'View cash register shifts and balances', 'cash_register'),
    ('cash_register.open', 'Open cash register', 'Open cash register shift', 'cash_register'),
    ('cash_register.close', 'Close cash register', 'Close cash register shift', 'cash_register'),
    ('cash_register.close_any', 'Close any cash register', 'Close another user''s cash register', 'cash_register'),
    ('cash_register.move', 'Create cash movement', 'Register manual cash movements', 'cash_register'),
    ('expenses.read', 'Read expenses', 'View administrative expenses', 'expenses'),
    ('expenses.create', 'Create expenses', 'Register administrative expenses', 'expenses'),
    ('expenses.update', 'Update expenses', 'Edit expenses from open cash sessions', 'expenses'),
    ('expenses.void', 'Void expenses', 'Void expenses without deleting financial history', 'expenses'),
    ('accounts_receivable.read', 'Read accounts receivable', 'View outstanding balances and overdue installments', 'accounts_receivable'),
    ('collections.read', 'Read collections', 'View collection cases', 'collections'),
    ('collections.create', 'Create collections', 'Create collection cases', 'collections'),
    ('collections.detect', 'Detect collections', 'Detect overdue installments and create cases', 'collections'),
    ('collections.update', 'Update collections', 'Update case status and assignment', 'collections'),
    ('collections.activities.create', 'Create collection activities', 'Register collection calls/messages', 'collections'),
    ('files.read', 'Read files', 'View patient files and attachments', 'documents'),
    ('files.upload', 'Upload files', 'Upload patient files and attachments', 'documents'),
    ('photographic_templates.view', 'View photographic templates', 'View orthodontic photographic sessions', 'clinical'),
    ('photographic_templates.create', 'Create photographic templates', 'Create orthodontic photographic sessions', 'clinical'),
    ('photographic_templates.edit', 'Edit photographic templates', 'Edit and complete photographic sessions', 'clinical'),
    ('photographic_templates.void', 'Void photographic templates', 'Void photographic sessions with a reason', 'clinical'),
    ('photographic_templates.link', 'Link photographic templates', 'Link sessions to appointments, controls and evolutions', 'clinical'),
    ('photographic_templates.mobile_upload', 'Create mobile photo uploads', 'Create secure short-lived mobile upload invitations', 'clinical'),
    ('photographic_templates.compare', 'Compare photographic templates', 'Compare equivalent photographic positions', 'clinical'),
    ('photographic_templates.view_voided', 'View voided photographic templates', 'View voided photographic clinical records', 'clinical'),
    ('photographic_templates.configure_frequency', 'Configure photographic frequency', 'Configure photographic reminder policy', 'clinical'),
    ('photographic_templates.configure_slots', 'Configure photographic positions', 'Configure photographic slot catalog', 'clinical'),
    ('photographic_photos.upload', 'Upload orthodontic photos', 'Upload photos into clinical positions', 'clinical'),
    ('photographic_photos.edit', 'Edit orthodontic photos', 'Apply non-destructive clinical image transformations', 'clinical'),
    ('photographic_photos.replace', 'Replace orthodontic photos', 'Replace a photo while preserving its history', 'clinical'),
    ('photographic_photos.void', 'Void orthodontic photos', 'Void a clinical photo with a reason', 'clinical'),
    ('consent_templates.read', 'Read consent templates', 'View consent templates', 'documents'),
    ('consent_templates.create', 'Create consent templates', 'Create consent templates', 'documents'),
    ('consent_templates.update', 'Update consent templates', 'Update consent templates', 'documents'),
    ('consent_templates.deactivate', 'Deactivate consent templates', 'Deactivate consent templates', 'documents'),
    ('consents.read', 'Read consents', 'View generated consents', 'documents'),
    ('consents.create', 'Create consents', 'Generate consents for patients', 'documents'),
    ('consents.sign', 'Sign consents', 'Sign and lock consents', 'documents'),
    ('consents.pdf', 'Download consent PDF', 'Download signed consent snapshot', 'documents'),
    ('consents.templates.read', 'Consultar plantillas de consentimiento', 'Ver plantillas y sus estados', 'documents'),
    ('consents.templates.create', 'Crear plantillas de consentimiento', 'Crear borradores de plantillas', 'documents'),
    ('consents.templates.update_draft', 'Editar borradores de consentimiento', 'Modificar solamente versiones en borrador', 'documents'),
    ('consents.templates.publish', 'Publicar plantillas de consentimiento', 'Publicar versiones inmutables', 'documents'),
    ('consents.templates.deactivate', 'Deshabilitar plantillas de consentimiento', 'Impedir nuevas instancias sin afectar documentos previos', 'documents'),
    ('consents.templates.view_versions', 'Consultar versiones de consentimiento', 'Ver historial de versiones', 'documents'),
    ('consents.templates.view_audit', 'Consultar auditoría de plantillas', 'Ver trazabilidad de plantillas', 'documents'),
    ('consents.instances.read', 'Consultar consentimientos clínicos', 'Ver consentimientos de pacientes', 'documents'),
    ('consents.instances.create', 'Generar consentimientos clínicos', 'Crear instancias desde versiones publicadas', 'documents'),
    ('consents.instances.complete_fields', 'Completar campos de consentimiento', 'Completar datos antes de la primera firma', 'documents'),
    ('consents.instances.sign_patient', 'Registrar firma del paciente', 'Capturar evidencia de firma del paciente', 'documents'),
    ('consents.instances.sign_professional', 'Registrar firma profesional', 'Capturar evidencia de firma profesional', 'documents'),
    ('consents.instances.sign_representative', 'Registrar firma del representante', 'Capturar evidencia de firma del representante', 'documents'),
    ('consents.instances.finalize', 'Finalizar consentimientos', 'Congelar contenido y generar PDF final', 'documents'),
    ('consents.instances.void', 'Anular consentimientos', 'Anular conservando documento y evidencia', 'documents'),
    ('consents.instances.download', 'Descargar consentimientos', 'Descargar PDF clínico final', 'documents'),
    ('consents.instances.view_evidence', 'Consultar evidencia de consentimiento', 'Ver hashes, firmas y auditoría', 'documents'),
    ('reports.read', 'Read reports', 'View dashboards and reports', 'reports'),
    ('reports.export', 'Export reports', 'Export reports in CSV/XLSX', 'reports'),
    ('lab_providers.read', 'Read lab providers', 'View laboratory providers', 'labs'),
    ('lab_providers.create', 'Create lab providers', 'Create laboratory providers', 'labs'),
    ('lab_providers.update', 'Update lab providers', 'Update laboratory providers', 'labs'),
    ('lab_providers.deactivate', 'Deactivate lab providers', 'Deactivate laboratory providers', 'labs'),
    ('lab_orders.read', 'Read lab orders', 'View laboratory orders', 'labs'),
    ('lab_orders.create', 'Create lab orders', 'Create laboratory orders', 'labs'),
    ('lab_orders.update', 'Update lab orders', 'Update laboratory order status', 'labs'),
    ('lab_orders.cost.update', 'Update lab order cost', 'Update laboratory order costs', 'labs'),
    ('lab_profitability.read', 'Read lab profitability', 'View treatment profitability with lab costs', 'labs'),
    ('suppliers.read', 'Read suppliers', 'View suppliers', 'inventory'),
    ('suppliers.create', 'Create suppliers', 'Create suppliers', 'inventory'),
    ('suppliers.update', 'Update suppliers', 'Update suppliers', 'inventory'),
    ('suppliers.deactivate', 'Deactivate suppliers', 'Deactivate suppliers', 'inventory'),
    ('inventory.read', 'Read inventory', 'View inventory items', 'inventory'),
    ('inventory.create', 'Create inventory items', 'Create inventory items', 'inventory'),
    ('inventory.update', 'Update inventory items', 'Update inventory items', 'inventory'),
    ('inventory.deactivate', 'Deactivate inventory items', 'Deactivate inventory items', 'inventory'),
    ('inventory.movements.read', 'Read inventory movements', 'View inventory movements', 'inventory'),
    ('inventory.movements.create', 'Create inventory movements', 'Create inventory movements', 'inventory'),
    ('inventory.alerts.read', 'Read inventory alerts', 'View minimum stock alerts', 'inventory'),
    ('inventory.warehouses.read', 'Read inventory warehouses', 'View inventory warehouses', 'inventory'),
    ('inventory.warehouses.manage', 'Manage inventory warehouses', 'Create and update inventory warehouses', 'inventory'),
    ('inventory.reports.read', 'Read inventory reports', 'Export inventory reports', 'inventory'),
    ('inventory.adjustments.create', 'Create inventory adjustments', 'Create stock adjustments', 'inventory'),
    ('inventory.sell', 'Sell inventory products', 'Register product sales from inventory', 'inventory'),
    ('inventory.products.view', 'View inventory products', 'View inventory product catalog and details', 'inventory'),
    ('inventory.products.create', 'Create inventory products', 'Create inventory products and catalog records', 'inventory'),
    ('inventory.products.update', 'Update inventory products', 'Update inventory products and catalog records', 'inventory'),
    ('inventory.products.reactivate', 'Reactivate inventory products', 'Reactivate inventory products', 'inventory'),
    ('inventory.entries.create', 'Create inventory entries', 'Post stock entries', 'inventory'),
    ('inventory.exits.create', 'Create inventory exits', 'Post stock exits', 'inventory'),
    ('inventory.transfers.create', 'Create inventory transfers', 'Transfer stock between warehouses', 'inventory'),
    ('inventory.waste.create', 'Create inventory waste', 'Post inventory waste movements', 'inventory'),
    ('inventory.movements.compensate', 'Compensate inventory movements', 'Create compensating inventory movements', 'inventory'),
    ('inventory.safety_stock.update', 'Update safety stock', 'Update warehouse safety stock thresholds', 'inventory'),
    ('inventory.reports.export', 'Export inventory reports', 'Export filtered inventory reports', 'inventory'),
    ('inventory.audit.view', 'View inventory audit', 'View inventory audit history', 'inventory'),
    ('inventory.costs.view', 'View inventory costs', 'View average cost and valuation', 'inventory'),
    ('inventory.stock_counts.create', 'Create stock counts', 'Create physical inventory counts', 'inventory'),
    ('inventory.stock_counts.reconcile', 'Reconcile stock counts', 'Reconcile physical inventory counts', 'inventory'),
    ('online_scheduling.read', 'Read online scheduling', 'View online scheduling config', 'settings'),
    ('online_scheduling.update', 'Update online scheduling', 'Update online scheduling config', 'settings'),
    ('treatment_plans.duplicate', 'Duplicate treatment plans', 'Duplicate treatment plans', 'treatment_plans'),
    ('treatment_plans.reactivate', 'Reactivate treatment plans', 'Reactivate cancelled treatment plans', 'treatment_plans'),
    ('treatment_plans.derive', 'Derive treatment plans', 'Transfer treatment plans between professionals', 'treatment_plans'),
    ('clinical.documents.delete', 'Delete clinical documents', 'Delete clinical documents logically', 'documents'),
    ('clinical.files.delete', 'Delete clinical files', 'Delete patient files logically', 'documents'),
    ('rx_analysis.run', 'Run RX Analysis', 'Run AI radiography analysis', 'documents'),
    ('collections.payroll_discounts.manage', 'Manage payroll discounts', 'Manage payroll discounts', 'collections'),
    ('reports.collections.read', 'Read collections reports', 'View collections and delinquency reports', 'reports'),
    ('price_list.view', 'View versioned price lists', 'View price lists and published versions', 'price_lists'),
    ('price_list.create', 'Create versioned price lists', 'Create price list drafts', 'price_lists'),
    ('price_list.edit_draft', 'Edit price list drafts', 'Edit draft versions and price items', 'price_lists'),
    ('price_list.publish', 'Publish price lists', 'Publish immutable price list versions', 'price_lists'),
    ('price_list.schedule', 'Schedule price lists', 'Schedule future price list versions', 'price_lists'),
    ('price_list.deactivate', 'Deactivate versioned price lists', 'Deactivate price list versions', 'price_lists'),
    ('price_list.compare_versions', 'Compare price list versions', 'Compare price list version changes', 'price_lists'),
    ('price_list.import', 'Import price lists', 'Import price list items', 'price_lists'),
    ('price_list.export', 'Export price lists', 'Export price list items', 'price_lists'),
    ('procedure.view', 'View clinical catalog', 'View procedure definitions', 'procedures'),
    ('procedure.create', 'Create clinical catalog items', 'Create procedure definitions', 'procedures'),
    ('procedure.edit', 'Edit clinical catalog items', 'Edit procedure definitions', 'procedures'),
    ('procedure.deactivate', 'Deactivate clinical catalog items', 'Deactivate procedure definitions', 'procedures'),
    ('price_template.view', 'View price templates', 'View reusable price templates', 'price_lists'),
    ('price_template.manage', 'Manage price templates', 'Create and publish price templates', 'price_lists'),
    ('price_override.apply', 'Apply price overrides', 'Apply a reasoned manual price override', 'price_lists'),
    ('price_override.approve', 'Approve price overrides', 'Approve price overrides above policy thresholds', 'price_lists'),
    ('agreement.apply_to_plan', 'Apply agreements to plans', 'Apply agreement pricing to treatment plans', 'agreements'),
    ('laboratory_price.view', 'View laboratory pricing', 'View laboratory price and cost', 'laboratories'),
    ('laboratory_price.edit', 'Edit laboratory pricing', 'Edit laboratory price and cost', 'laboratories'),
    ('price_audit.view', 'View pricing audit', 'View price resolution and publication audit', 'price_lists'),
    ('patients.files.manage', 'Manage patient files', 'Delete patient file attachments', 'documents'),
    ('integrations.communications.read', 'Read communication jobs', 'View email, WhatsApp and internal delivery jobs', 'integrations'),
    ('integrations.communications.send', 'Send communication jobs', 'Create and queue patient communications', 'integrations'),
    ('integrations.surveys.read', 'Read surveys', 'View surveys and NPS responses', 'integrations'),
    ('integrations.surveys.manage', 'Manage surveys', 'Create and send surveys', 'integrations'),
    ('integrations.chat.read', 'Read chat', 'View internal chat messages', 'integrations'),
    ('integrations.chat.send', 'Send chat', 'Create internal chat messages', 'integrations'),
    ('integrations.telemedicine.read', 'Read telemedicine', 'View telemedicine sessions', 'integrations'),
    ('integrations.telemedicine.manage', 'Manage telemedicine', 'Create and update telemedicine sessions', 'integrations'),
    ('integrations.imports.read', 'Read import jobs', 'View bulk import jobs', 'integrations'),
    ('integrations.imports.manage', 'Manage import jobs', 'Create and update bulk import jobs', 'integrations'),
    ('integrations.ai.read', 'Read AI requests', 'View AI request and result logs', 'integrations'),
    ('integrations.ai.request', 'Create AI requests', 'Create AI analysis requests', 'integrations'),
    ('integrations.ai.complete', 'Complete AI requests', 'Store AI results after provider processing', 'integrations'),
    ('document_requirements.read', 'Read document requirements', 'View required clinical documents', 'documents'),
    ('document_requirements.manage', 'Manage document requirements', 'Create required clinical documents', 'documents'),
    ('document_requirements.satisfy', 'Satisfy document requirements', 'Attach evidence to required documents', 'documents'),
    ('document_requirements.waive', 'Waive document requirements', 'Waive required documents with reason', 'documents'),
    ('payment_webhooks.read', 'Read payment webhooks', 'View payment provider webhook events', 'payments'),
    ('payment_webhooks.manage', 'Manage payment webhooks', 'Process payment provider webhook events', 'payments')
)
INSERT INTO "Permission" (
  "id", "key", "name", "description", "module", "code", "action", "resource",
  "isSystem", "isActive", "createdAt", "updatedAt"
)
SELECT
  'perm_catalog_' || substr(md5(ps."key"), 1, 18),
  ps."key", ps."name", ps."description", ps."module", ps."key",
  split_part(ps."key", '.', 2), split_part(ps."key", '.', 1),
  true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM permission_seed ps
ON CONFLICT ("key") DO UPDATE SET
  "name" = EXCLUDED."name",
  "description" = EXCLUDED."description",
  "module" = EXCLUDED."module",
  "code" = EXCLUDED."code",
  "action" = EXCLUDED."action",
  "resource" = EXCLUDED."resource",
  "isActive" = true,
  "updatedAt" = CURRENT_TIMESTAMP;
