import { Link, useLocation } from "react-router-dom";
import { APP_ROUTES } from "@/lib/routes";

const mapName: Record<string, string> = {
  panel: "Panel",
  dashboard: "Panel",
  agenda: "Agenda",
  lista: "Lista",
  list: "Lista",
  dia: "Día",
  day: "Día",
  semana: "Semana",
  week: "Semana",
  mes: "Mes",
  month: "Mes",
  imprimir: "Imprimir",
  print: "Imprimir",
  reprogramacion: "Reprogramación",
  reprogramming: "Reprogramación",
  "waiting-room": "Sala de espera",
  pacientes: "Pacientes",
  patients: "Pacientes",
  nuevo: "Nuevo",
  new: "Nuevo",
  "calidad-datos": "Calidad de datos",
  "data-quality": "Calidad de datos",
  fusion: "Fusión",
  merge: "Fusión",
  configuracion: "Configuración",
  settings: "Configuración",
  perfil: "Perfil",
  profile: "Perfil",
  organizacion: "Organización",
  organization: "Organización",
  logotipo: "Logotipo",
  logo: "Logotipo",
  bancos: "Bancos",
  banks: "Bancos",
  convenios: "Convenios",
  agreements: "Convenios",
  gastos: "Gastos",
  expenses: "Gastos",
  nominas: "Nóminas",
  payroll: "Nóminas",
  "planes-servicios": "Planes y servicios",
  plans: "Planes y servicios",
  sucursales: "Sucursales",
  branches: "Sucursales",
  profesionales: "Profesionales",
  professionals: "Profesionales",
  especialidades: "Especialidades",
  specialties: "Especialidades",
  "agenda-online": "Agenda Online",
  "online-scheduling": "Agenda Online",
  express: "Express",
  horarios: "Horarios",
  schedules: "Horarios",
  campanas: "Campañas",
  campaigns: "Campañas",
  sillones: "Sillones",
  chairs: "Sillones",
  "medios-pago": "Medios de pago",
  "payment-methods": "Medios de pago",
  "liquidaciones-pagos": "Recepciones programadas",
  "payment-settlements": "Recepciones programadas",
  procedimientos: "Procedimientos",
  procedures: "Procedimientos",
  "listas-precios": "Listas de precios",
  "price-lists": "Listas de precios",
  "plantillas-consentimiento": "Plantillas consentimiento",
  "consent-templates": "Plantillas consentimiento",
  "documentos-clinicos": "Documentos clínicos",
  "clinical-documents": "Documentos clínicos",
  "planes-tratamiento": "Planes",
  "treatment-plans": "Planes",
  presupuestos: "Presupuestos",
  budgets: "Presupuestos",
  cajas: "Cajas",
  "cash-register": "Cajas",
  abiertas: "Abiertas",
  open: "Abiertas",
  cerradas: "Cerradas",
  closed: "Cerradas",
  buscar: "Buscar",
  search: "Buscar",
  "cuentas-por-cobrar": "Cuentas por cobrar",
  "accounts-receivable": "Cuentas por cobrar",
  cuotas: "Cuotas",
  installments: "Cuotas",
  morosidad: "Morosidad",
  collections: "Morosidad",
  usuarios: "Usuarios",
  users: "Usuarios",
  bloqueos: "Bloqueos",
  blocks: "Bloqueos",
  acceso: "Acceso",
  access: "Acceso",
  contratos: "Contratos",
  contracts: "Contratos",
  masivos: "Masivos",
  bulk: "Masivos",
  roles: "Roles",
  "iniciar-sesion": "Iniciar sesión",
  login: "Iniciar sesión",
  clinica: "Clínica",
  clinical: "Clínica",
  historia: "Historia",
  history: "Historia",
  evoluciones: "Evoluciones",
  evolutions: "Evoluciones",
  anamnesis: "Anamnesis",
  "medical-history": "Anamnesis",
  recetas: "Recetas",
  prescriptions: "Recetas",
  documentos: "Documentos",
  documents: "Documentos",
  odontograma: "Odontograma",
  odontogram: "Odontograma",
  periodontograma: "Periodontograma",
  periodontogram: "Periodontograma",
  citas: "Citas",
  appointments: "Citas",
  tratamientos: "Tratamientos",
  treatments: "Tratamientos",
  pagos: "Pagos",
  payments: "Pagos",
  consentimientos: "Consentimientos",
  consents: "Consentimientos",
  archivos: "Archivos",
  files: "Archivos",
  facturacion: "Facturación",
  billing: "Facturación",
  coberturas: "Coberturas",
  coverages: "Coberturas",
  reembolsos: "Reembolsos",
  reimbursements: "Reembolsos",
  "beneficios-online": "Beneficios Online",
  "online-benefits": "Beneficios Online",
  devoluciones: "Devoluciones",
  refunds: "Devoluciones",
  anulados: "Anulados",
  "anulados-pendientes": "Anulados y pendientes",
  saldo: "Saldo",
  balance: "Saldo",
  inventario: "Inventario",
  inventory: "Inventario",
  movimientos: "Movimientos",
  movements: "Movimientos",
  laboratorios: "Laboratorios",
  labs: "Laboratorios",
  habilitados: "Habilitados",
  enabled: "Habilitados",
  ordenes: "Órdenes",
  orders: "Órdenes",
  reportes: "Reportes",
  reports: "Reportes",
  desempeno: "Desempeño",
  performance: "Desempeño",
  excel: "Excel",
  graficos: "Gráficos",
  charts: "Gráficos",
  financiero: "Financiero",
  financial: "Financiero",
  crm: "CRM",
  encuestas: "Encuestas",
  surveys: "Encuestas",
  resultados: "Resultados",
  results: "Resultados",
  "configuracion-envio": "Configuración de envío",
  "send-config": "Configuración de envío",
  "email-marketing": "Email Marketing",
  campana: "Campaña",
  campaign: "Campaña",
  plantillas: "Plantillas",
  templates: "Plantillas",
  tareas: "Tareas",
  tasks: "Tareas",
  estadisticas: "Estadísticas",
  statistics: "Estadísticas",
  "centro-salud": "Centro de Salud",
  "health-center": "Centro de Salud"
};

export function Breadcrumbs() {
  const location = useLocation();
  const pieces = location.pathname.split("/").filter(Boolean);

  const paths = pieces.map((piece, index) => {
    const to = `/${pieces.slice(0, index + 1).join("/")}`;
    return {
      to,
      label: mapName[piece] ?? piece
    };
  });

  return (
    <nav className="text-sm text-slate-500">
      <ol className="flex items-center gap-2">
        <li>
          <Link to={APP_ROUTES.agenda.list} className="hover:text-slate-700">
            Inicio
          </Link>
        </li>
        {paths.map((path) => (
          <li key={path.to} className="flex items-center gap-2">
            <span>/</span>
            <Link to={path.to} className="hover:text-slate-700">
              {path.label}
            </Link>
          </li>
        ))}
      </ol>
    </nav>
  );
}
