-- AlterTable
ALTER TABLE "Branch" ADD COLUMN "agendaSlotMinutes" INTEGER NOT NULL DEFAULT 30;
ALTER TABLE "Branch" ADD COLUMN "agendaStartHour" INTEGER NOT NULL DEFAULT 8;
ALTER TABLE "Branch" ADD COLUMN "agendaEndHour" INTEGER NOT NULL DEFAULT 19;
